import {EditorState,Compartment,Prec} from '@codemirror/state';
import {EditorView,keymap,hoverTooltip} from '@codemirror/view';
import {basicSetup} from 'codemirror';
import {liveEditorExtensions,liveRefreshEffect} from './live-editor.js';
import {indentWithTab,undo,redo,toggleComment,copyLineDown,isolateHistory} from '@codemirror/commands';
import {syntaxHighlighting,HighlightStyle,foldService,indentUnit} from '@codemirror/language';
import {tags} from '@lezer/highlight';
import {autocompletion,acceptCompletion,completionStatus,startCompletion} from '@codemirror/autocomplete';
export const normalizeEditorText=text=>text==null?text:String(text).replace(/\r\n?/g,'\n');
export const germanEditorPhrases={"Completions":"Vervollständigungen","Find":"Suchen","Replace":"Ersetzen","next":"weiter","previous":"zurück","all":"alle","match case":"Groß-/Kleinschreibung","regexp":"Regulärer Ausdruck","by word":"Ganzes Wort","replace":"ersetzen","replace all":"alle ersetzen","close":"schließen","Go to line":"Gehe zu Zeile","go":"Los","current match":"Aktueller Treffer","on line":"in Zeile","replaced match on line $":"Treffer in Zeile $ ersetzt","replaced $ matches":"$ Treffer ersetzt","Fold line":"Zeile einklappen","Unfold line":"Zeile ausklappen","folded code":"Eingeklappter Code","unfold":"ausklappen","Folded lines":"Eingeklappte Zeilen","Unfolded lines":"Ausgeklappte Zeilen","to":"bis","Control character":"Steuerzeichen"};
import {argent} from './argent-language.js';
export {argent};
export function createEditor(host,options={}){
 const config=new Compartment(),readOnly=new Compartment();let ignore=false;
 const live=Boolean(options.language)&&options.live!==false;
 const settings=()=>options.getSettings?.()||{};
 const theme=()=>{const dark=settings().darkMode;return [EditorState.phrases.of(settings().language==='en'?{}:germanEditorPhrases),EditorView.theme({'&':{height:'100%',fontSize:'14px',backgroundColor:dark?'#161a20':'#fff',color:dark?'#dce4f0':'#192733'},'.cm-scroller':{fontFamily:'Consolas, Menlo, monospace',lineHeight:'1.48'},'.cm-gutters':{backgroundColor:dark?'#1b2028':'#f5f8fc',color:dark?'#76889d':'#69798c',borderRight:'1px solid '+(dark?'#37414f':'#d4dce5')},'.cm-activeLine':{backgroundColor:dark?'#1f2732':'#f4f8fd'},'.cm-activeLineGutter':{backgroundColor:dark?'#1f2732':'#e2eefb'},'&.cm-focused .cm-selectionBackground, .cm-selectionBackground':{backgroundColor:dark?'#344e6f!important':'#b9d9fc!important'},'.cm-cursor':{borderLeftColor:dark?'white':'black'}},{dark}),syntaxHighlighting(HighlightStyle.define([{tag:tags.keyword,color:dark?'#c391f2':'#7f2daa'},{tag:tags.comment,color:dark?'#779e70':'#4a7c46'},{tag:tags.string,color:dark?'#d89b7e':'#a53732'},{tag:tags.number,color:dark?'#ebb975':'#9e4f00'},{tag:tags.typeName,color:dark?'#4fc9b0':'#007864'}])),settings().wordWrap?EditorView.lineWrapping:[]];};
 const view=new EditorView({parent:host,state:EditorState.create({doc:options.text||'',extensions:[live?liveEditorExtensions({getSettings:settings,inspectProject:options.inspectProject,getProjectRevision:options.getProjectRevision,onNavigate:options.onNavigate,semanticChecks:options.semanticChecks!==false}):[],Prec.highest(keymap.of([{key:'Mod-z',run:()=>options.history?.(false)||false},{key:'Mod-y',run:()=>options.history?.(true)||false},{key:'Mod-Shift-z',run:()=>options.history?.(true)||false},{key:'Tab',run:v=>{if(completionStatus(v.state)==='active'){acceptCompletion(v);return true;}return indentWithTab.run(v);}},{key:'Shift-Tab',run:indentWithTab.shift},{key:'Mod-d',run:copyLineDown}])),basicSetup,argent,indentUnit.of('    '),foldService.of((state,start,end)=>{const first=state.doc.lineAt(start);if(!first.text.includes('{'))return null;let depth=0,found=false;for(let n=first.number;n<=state.doc.lines;n++){const line=state.doc.line(n),code=line.text.replace(/\/\/.*$/,'');for(let i=0;i<code.length;i++){if(code[i]==='{'){depth++;found=true;}else if(code[i]==='}'&&found&&--depth===0)return n>first.number?{from:end,to:line.from+i}:null;}}return null;}),config.of(theme()),readOnly.of(EditorState.readOnly.of(!!options.readOnly)),keymap.of([{key:'Tab',run:indentWithTab.run},{key:'Mod-d',run:copyLineDown},{key:'Mod-/',run:toggleComment},{key:'F12',run:()=>{options.definition?.(view.state.selection.main.head);return true;}}]),autocompletion({activateOnTyping:!live,override:[async c=>{if(!options.language)return null;const word=c.matchBefore(/[\w]*/);if(!c.explicit&&(!word||word.text.length<2)&&c.state.sliceDoc(Math.max(0,c.pos-1),c.pos)!=='.')return null;try{const data=await options.language(c.pos);return {from:word?.from??c.pos,options:(data.items||[]).map(x=>({label:x.name,detail:x.detail,info:x.documentation||'',type:x.kind==='fn'?'function':x.kind==='keyword'?'keyword':'variable'}))};}catch{return null;}}]}),hoverTooltip(async(v,pos)=>{if(!options.language)return null;try{const data=await options.language(pos,'hover');const tip=data.hover||data;const text=tip.detail||tip.signature||tip.documentation;if(!text)return null;return {pos,create(){const dom=document.createElement('div');dom.className='code-tooltip';dom.textContent=text;if(settings().aiHover&&options.aiExplain&&options.canShare?.()){const action=document.createElement('button');action.textContent=settings().language==='en'?'Explain with AI':'Mit KI erklären';action.onclick=()=>options.aiExplain(pos);dom.append(document.createElement('br'),action);}return {dom};}};}catch{return null;}}),EditorView.updateListener.of(u=>{if(u.docChanged&&!ignore)options.onChange?.(u.state.doc.toString());if(u.selectionSet||u.docChanged)options.onSelection?.(u.state.selection.main.head,u.state.doc);})]})});
 return {view,refreshLive(){if(live)view.dispatch({effects:liveRefreshEffect.of(null)});},complete:()=>startCompletion(view),getText:()=>view.state.doc.toString(),setText(text){text=normalizeEditorText(text);if(text===view.state.doc.toString())return;ignore=true;const old=view.state.doc.toString();let from=0,endOld=old.length,endNew=text.length;while(from<endOld&&from<endNew&&old[from]===text[from])from++;while(endOld>from&&endNew>from&&old[endOld-1]===text[endNew-1]){endOld--;endNew--;}view.dispatch({changes:{from,to:endOld,insert:text.slice(from,endNew)},annotations:isolateHistory.of('full')});ignore=false;},setReadOnly(value){view.dispatch({effects:readOnly.reconfigure(EditorState.readOnly.of(value))});},refresh(){view.dispatch({effects:config.reconfigure(theme())});},focus(){view.focus();},select(position,length=0){const p=Math.max(0,Math.min(position,view.state.doc.length));view.dispatch({selection:{anchor:p,head:Math.min(p+length,view.state.doc.length)},effects:EditorView.scrollIntoView(p,{y:'center'})});view.focus();},undo(){return undo(view);},redo(){return redo(view);},destroy(){view.destroy();}};
}
