import {normalizeReviewFindings} from './review-findings.js';
import {proposalHunks,proposalMatches} from './inline-proposals.js';
import './inline-proposals.css';
import {EditorState,Compartment,Prec,StateEffect,StateField,RangeSet} from '@codemirror/state';
import {EditorView,keymap,hoverTooltip,showPanel,Decoration,gutter,GutterMarker,showTooltip} from '@codemirror/view';
import {basicSetup} from 'codemirror';
import {liveEditorExtensions,liveRefreshEffect} from './live-editor.js';
import {indentWithTab,undo,redo,toggleComment,copyLineDown,isolateHistory} from '@codemirror/commands';
import {syntaxHighlighting,HighlightStyle,foldService,indentUnit} from '@codemirror/language';
import {editorFontSize,mountZoomControls} from './editor-zoom.js';
import {tags} from '@lezer/highlight';
import {autocompletion,acceptCompletion,completionStatus,startCompletion} from '@codemirror/autocomplete';
export const normalizeEditorText=text=>text==null?text:String(text).replace(/\r\n?/g,'\n');
export const germanEditorPhrases={"Completions":"Vervollständigungen","Find":"Suchen","Replace":"Ersetzen","next":"weiter","previous":"zurück","all":"alle","match case":"Groß-/Kleinschreibung","regexp":"Regulärer Ausdruck","by word":"Ganzes Wort","replace":"ersetzen","replace all":"alle ersetzen","close":"schließen","Go to line":"Gehe zu Zeile","go":"Los","current match":"Aktueller Treffer","on line":"in Zeile","replaced match on line $":"Treffer in Zeile $ ersetzt","replaced $ matches":"$ Treffer ersetzt","Fold line":"Zeile einklappen","Unfold line":"Zeile ausklappen","folded code":"Eingeklappter Code","unfold":"ausklappen","Folded lines":"Eingeklappte Zeilen","Unfolded lines":"Ausgeklappte Zeilen","to":"bis","Control character":"Steuerzeichen"};
import {argent} from './argent-language.js';
export {argent};
export function createEditor(host,options={}){
 const config=new Compartment(),readOnly=new Compartment();let ignore=false;
 const live=Boolean(options.language)&&options.live!==false;
 const settings=()=>options.getSettings?.()||{};
 const proposalEffect=StateEffect.define(),openProposalEffect=StateEffect.define();
 const proposalField=StateField.define({create:()=>null,update(value,tr){
  if(tr.docChanged||tr.state.readOnly)value=null;
  for(const effect of tr.effects){if(effect.is(proposalEffect))value=proposalMatches(effect.value,tr.state.doc.toString(),tr.state.readOnly)?{...effect.value,hunks:proposalHunks(effect.value.before,effect.value.after),open:null}:null;
   if(effect.is(openProposalEffect)&&value)value={...value,open:effect.value};}return value;
 }});
 const reviewEffect=StateEffect.define(),openReviewEffect=StateEffect.define();
 const reviewField=StateField.define({create:()=>null,update(value,tr){
  if(tr.docChanged||tr.state.readOnly)value=null;
  for(const effect of tr.effects){if(effect.is(reviewEffect))value=normalizeReviewFindings(effect.value,tr.state.doc.toString(),tr.state.readOnly);
   if(effect.is(openReviewEffect)&&value)value={...value,open:effect.value};}return value;
 }});
 const reviewWords=()=>settings().language==='en'?{title:'AI review note',current:'Current code',suggestion:'Suggested code (unverified)',note:'This is a review note. A concrete change must be prepared and verified before it can be applied.',prepare:'Prepare change',marker:'Show AI review note',close:'Close'}:{title:'KI-Prüfhinweis',current:'Aktueller Code',suggestion:'Vorgeschlagener Code (ungeprüft)',note:'Dies ist ein Prüfhinweis. Eine konkrete Änderung muss vor der Übernahme ausgearbeitet und geprüft werden.',prepare:'Änderung ausarbeiten',marker:'KI-Prüfhinweis anzeigen',close:'Schließen'};
 const proposalAt=(state,line)=>state.field(proposalField)?.hunks.findIndex(h=>line>=Math.min(h.fromLine,state.doc.lines)&&line<=Math.min(Math.max(h.toLine,h.fromLine),state.doc.lines))??-1;
 function reviewTooltip(v,index,state=v.state){const review=state.field(reviewField),finding=review?.findings[index];if(!finding)return null;
  return {pos:state.doc.line(finding.startLine).from,end:state.doc.line(finding.endLine).to,above:true,create(){
   const w=reviewWords(),dom=document.createElement('div');dom.className='cm-ai-tooltip cm-ai-review-tooltip cm-review-tooltip'+(settings().darkMode?' cm-ai-tooltip-dark':'');dom.setAttribute('role','dialog');dom.setAttribute('aria-label',w.title);
   const title=document.createElement('h4');title.textContent=finding.title;const message=document.createElement('p');message.textContent=finding.message;dom.append(title,message);
   for(const [label,text] of [[w.current,state.doc.sliceString(state.doc.line(finding.startLine).from,state.doc.line(finding.endLine).to)],...(finding.suggestion!=null?[[w.suggestion,finding.suggestion]]:[])]){const heading=document.createElement('strong');heading.textContent=label;const code=document.createElement('pre');code.textContent=text;dom.append(heading,code);}
   const note=document.createElement('p');note.textContent=w.note;dom.append(note);
   if(review.onRequestProposal){const prepare=document.createElement('button');prepare.type='button';prepare.textContent=w.prepare;prepare.onclick=()=>{const current=v.state.field(reviewField);if(current!==review||v.state.readOnly||current.before!==v.state.doc.toString())return;current.onRequestProposal(finding);};dom.append(prepare);}
   const close=document.createElement('button');close.type='button';close.textContent=w.close;close.onclick=()=>{v.dispatch({effects:openReviewEffect.of(null)});v.focus();};dom.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close.click();}});dom.append(close);return {dom};
  }};
 }
 class ReviewMarker extends GutterMarker{
  constructor(index){super();this.index=index;this.label=reviewWords().marker;}eq(other){return this.index===other.index&&this.label===other.label;}
  toDOM(v){const button=document.createElement('button');button.type='button';button.className='cm-ai-marker cm-ai-review-marker cm-review-marker';button.textContent='◇';button.dataset.reviewIndex=String(this.index);button.setAttribute('aria-label',this.label);button.title=this.label;
   requestAnimationFrame(()=>{const group=button.closest('.cm-gutters');if(group){group.removeAttribute('aria-hidden');for(const column of group.children)if(!column.classList.contains('cm-ai-gutter')&&!column.classList.contains('cm-ai-review-gutter'))column.setAttribute('aria-hidden','true');}});
   button.onclick=()=>{const review=v.state.field(reviewField),finding=review?.findings[this.index];if(!finding)return;const proposal=proposalAt(v.state,finding.startLine);v.dispatch({effects:proposal>=0?openProposalEffect.of(proposal):openReviewEffect.of(this.index)});requestAnimationFrame(()=>v.dom.querySelector('.cm-ai-tooltip button:not(:disabled)')?.focus());};return button;}
 }
 const reviewExtensions=[reviewField,EditorView.decorations.compute([reviewField],state=>{
  const positions=new Set();for(const finding of state.field(reviewField)?.findings||[])for(let n=finding.startLine;n<=finding.endLine;n++)positions.add(state.doc.line(n).from);
  return Decoration.set([...positions].map(pos=>Decoration.line({class:'cm-ai-review'}).range(pos)),true);
 }),gutter({class:'cm-ai-review-gutter',markers:v=>RangeSet.of((v.state.field(reviewField)?.findings||[]).map((finding,index)=>new ReviewMarker(index).range(v.state.doc.line(finding.startLine).from)),true)}),
 showTooltip.compute([reviewField,proposalField],state=>{const index=state.field(reviewField)?.open;return index==null||state.field(proposalField)?.open!=null?null:reviewTooltip(view,index,state);}),
 hoverTooltip((v,pos)=>{const review=v.state.field(reviewField);if(!review||review.open!=null||v.state.field(proposalField)?.open!=null)return null;const line=v.state.doc.lineAt(pos).number;if(proposalAt(v.state,line)>=0)return null;const index=review.findings.findIndex(f=>line>=f.startLine&&line<=f.endLine);return index<0?null:reviewTooltip(v,index);},{hoverTime:250,hideOn:tr=>!tr.state.field(reviewField)||tr.effects.some(effect=>effect.is(reviewEffect)||effect.is(openReviewEffect)||effect.is(proposalEffect)||effect.is(openProposalEffect))})];
 const words=()=>settings().language==='en'?{title:'AI code suggestion',before:'Before',after:'After',empty:'(no lines)',apply:'Apply all changes',discard:'Discard all changes',scope:'This preview shows one block. Apply accepts the entire verified proposal.',waiting:'Verification is pending.',marker:'Show AI change',close:'Close'}:{title:'KI-Codevorschlag',before:'Vorher',after:'Nachher',empty:'(keine Zeilen)',apply:'Alle Änderungen übernehmen',discard:'Alle Änderungen verwerfen',scope:'Diese Vorschau zeigt einen Block. Übernehmen wendet den gesamten geprüften Vorschlag an.',waiting:'Prüfung steht noch aus.',marker:'KI-Änderung anzeigen',close:'Schließen'};
 const hunkPosition=(state,hunk)=>state.doc.line(Math.min(hunk.fromLine,state.doc.lines)).from;
 function proposalTooltip(v,index,state=v.state){const proposal=state.field(proposalField),hunk=proposal?.hunks[index];if(!hunk)return null;
  return {pos:hunkPosition(state,hunk),end:state.doc.line(Math.min(Math.max(hunk.toLine,hunk.fromLine),state.doc.lines)).to,above:true,create(){
   const w=words(),dom=document.createElement('div');dom.className='cm-ai-tooltip'+(settings().darkMode?' cm-ai-tooltip-dark':'');dom.setAttribute('role','dialog');dom.setAttribute('aria-label',w.title);
   const title=document.createElement('h4');title.textContent=w.title;dom.append(title);
   const comparison=document.createElement('div');comparison.className='cm-ai-comparison';
   for(const [label,text,count,cls] of [[w.before,hunk.before,hunk.removedLines,'cm-ai-before'],[w.after,hunk.after,hunk.addedLines,'cm-ai-after']]){const section=document.createElement('div');section.className=cls;const heading=document.createElement('strong');heading.textContent=label;const code=document.createElement('pre');code.textContent=count?text:w.empty;section.append(heading,code);comparison.append(section);}dom.append(comparison);
   const scope=document.createElement('p');scope.textContent=w.scope;dom.append(scope);
   if(proposal.message||!proposal.ready||proposal.busy){const status=document.createElement('p');status.textContent=proposal.message||w.waiting;dom.append(status);}
   const apply=document.createElement('button');apply.type='button';apply.textContent=w.apply;apply.disabled=!proposal.ready||proposal.busy;
   apply.onclick=()=>{const current=v.state.field(proposalField);if(current!==proposal||!current.ready||current.busy||!proposalMatches(current,v.state.doc.toString(),v.state.readOnly))return;current.onApply?.();};
   const discard=document.createElement('button');discard.type='button';discard.textContent=w.discard;discard.disabled=!!proposal.busy;discard.onclick=()=>{if(v.state.field(proposalField)!==proposal)return;v.dispatch({effects:proposalEffect.of(null)});proposal.onDiscard?.();};
   const close=document.createElement('button');close.type='button';close.textContent=w.close;close.onclick=()=>{v.dispatch({effects:openProposalEffect.of(null)});v.focus();};
   dom.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close.click();}});dom.append(apply,discard,close);return {dom};
  }};
 }
 class ProposalMarker extends GutterMarker{
  constructor(index){super();this.index=index;this.label=words().marker;}eq(other){return this.index===other.index&&this.label===other.label;}
  toDOM(v){const button=document.createElement('button');button.type='button';button.className='cm-ai-marker';button.textContent='✦';button.setAttribute('aria-label',this.label);button.title=this.label;requestAnimationFrame(()=>{const group=button.closest('.cm-gutters');if(group){group.removeAttribute('aria-hidden');for(const column of group.children)if(!column.classList.contains('cm-ai-gutter')&&!column.classList.contains('cm-ai-review-gutter'))column.setAttribute('aria-hidden','true');}});
   button.onclick=()=>{v.dispatch({effects:openProposalEffect.of(this.index)});requestAnimationFrame(()=>v.dom.querySelector('.cm-ai-tooltip button:not(:disabled)')?.focus());};return button;}
 }
 const proposalExtensions=[proposalField,EditorView.decorations.compute([proposalField],state=>{
  const marks=[],positions=new Set();for(const hunk of state.field(proposalField)?.hunks||[]){const first=Math.min(hunk.fromLine,state.doc.lines),last=Math.min(Math.max(hunk.toLine,first),state.doc.lines);for(let line=first;line<=last;line++){const position=state.doc.line(line).from;if(!positions.has(position)){positions.add(position);marks.push(Decoration.line({class:'cm-ai-change'}).range(position));}}}return Decoration.set(marks,true);
 }),gutter({class:'cm-ai-gutter',markers:v=>RangeSet.of((v.state.field(proposalField)?.hunks||[]).map((hunk,index)=>new ProposalMarker(index).range(hunkPosition(v.state,hunk))),true)}),
 showTooltip.compute([proposalField],state=>{const index=state.field(proposalField)?.open;return index==null?null:proposalTooltip(view,index,state);}),
 hoverTooltip((v,pos)=>{const proposal=v.state.field(proposalField);if(!proposal||proposal.open!=null)return null;const line=v.state.doc.lineAt(pos).number;const index=proposal.hunks.findIndex(hunk=>line>=Math.min(hunk.fromLine,v.state.doc.lines)&&line<=Math.min(Math.max(hunk.toLine,hunk.fromLine),v.state.doc.lines));return index<0?null:proposalTooltip(v,index);},{hoverTime:250,hideOn:tr=>!tr.state.field(proposalField)||tr.effects.some(effect=>effect.is(proposalEffect)||effect.is(openProposalEffect))})];
 const theme=()=>{const dark=settings().darkMode;return [EditorState.phrases.of(settings().language==='en'?{}:germanEditorPhrases),EditorView.theme({'&':{height:'100%',fontSize:editorFontSize(settings()),backgroundColor:dark?'#161a20':'#fff',color:dark?'#dce4f0':'#192733'},'.cm-scroller':{fontSize:editorFontSize(settings()),fontFamily:'Consolas, Menlo, monospace',lineHeight:'1.48'},'.cm-gutters':{backgroundColor:dark?'#1b2028':'#f5f8fc',color:dark?'#76889d':'#69798c',borderRight:'1px solid '+(dark?'#37414f':'#d4dce5')},'.cm-activeLine':{backgroundColor:dark?'#1f2732':'#f4f8fd'},'.cm-activeLineGutter':{backgroundColor:dark?'#1f2732':'#e2eefb'},'&.cm-focused .cm-selectionBackground, .cm-selectionBackground':{backgroundColor:dark?'#344e6f!important':'#b9d9fc!important'},'.cm-cursor':{borderLeftColor:dark?'white':'black'}},{dark}),syntaxHighlighting(HighlightStyle.define([{tag:tags.keyword,color:dark?'#c391f2':'#7f2daa'},{tag:tags.comment,color:dark?'#779e70':'#4a7c46'},{tag:tags.string,color:dark?'#d89b7e':'#a53732'},{tag:tags.number,color:dark?'#ebb975':'#9e4f00'},{tag:tags.typeName,color:dark?'#4fc9b0':'#007864'}])),settings().wordWrap?EditorView.lineWrapping:[]];};
 const view=new EditorView({parent:host,state:EditorState.create({doc:options.text||'',extensions:[proposalExtensions,reviewExtensions,options.zoomContext?showPanel.of(()=>{const dom=mountZoomControls(options.zoomContext);return {dom,top:false,update:()=>dom.refresh()};}):[],live?liveEditorExtensions({getSettings:settings,inspectProject:options.inspectProject,getProjectRevision:options.getProjectRevision,onNavigate:options.onNavigate,semanticChecks:options.semanticChecks!==false}):[],Prec.highest(keymap.of([{key:'Mod-z',run:()=>options.history?.(false)||false},{key:'Mod-y',run:()=>options.history?.(true)||false},{key:'Mod-Shift-z',run:()=>options.history?.(true)||false},{key:'Tab',run:v=>{if(completionStatus(v.state)==='active'){acceptCompletion(v);return true;}return indentWithTab.run(v);}},{key:'Shift-Tab',run:indentWithTab.shift},{key:'Mod-d',run:copyLineDown}])),basicSetup,argent,indentUnit.of('    '),foldService.of((state,start,end)=>{const first=state.doc.lineAt(start);if(!first.text.includes('{'))return null;let depth=0,found=false;for(let n=first.number;n<=state.doc.lines;n++){const line=state.doc.line(n),code=line.text.replace(/\/\/.*$/,'');for(let i=0;i<code.length;i++){if(code[i]==='{'){depth++;found=true;}else if(code[i]==='}'&&found&&--depth===0)return n>first.number?{from:end,to:line.from+i}:null;}}return null;}),config.of(theme()),readOnly.of(EditorState.readOnly.of(!!options.readOnly)),keymap.of([{key:'Tab',run:indentWithTab.run},{key:'Mod-d',run:copyLineDown},{key:'Mod-/',run:toggleComment},{key:'F12',run:()=>{options.definition?.(view.state.selection.main.head);return true;}}]),autocompletion({activateOnTyping:!live,override:[async c=>{if(!options.language)return null;const word=c.matchBefore(/[\w]*/);if(!c.explicit&&(!word||word.text.length<2)&&c.state.sliceDoc(Math.max(0,c.pos-1),c.pos)!=='.')return null;try{const data=await options.language(c.pos);return {from:word?.from??c.pos,options:(data.items||[]).map(x=>({label:x.name,detail:x.detail,info:x.documentation||'',type:x.kind==='fn'?'function':x.kind==='keyword'?'keyword':'variable'}))};}catch{return null;}}]}),hoverTooltip(async(v,pos)=>{if(!options.language)return null;try{const data=await options.language(pos,'hover');const tip=data.hover||data;const text=tip.detail||tip.signature||tip.documentation;if(!text)return null;return {pos,create(){const dom=document.createElement('div');dom.className='code-tooltip';dom.textContent=text;if(settings().aiHover&&options.aiExplain&&options.canShare?.()){const action=document.createElement('button');action.textContent=settings().language==='en'?'Explain with AI':'Mit KI erklären';action.onclick=()=>options.aiExplain(pos);dom.append(document.createElement('br'),action);}return {dom};}};}catch{return null;}}),EditorView.updateListener.of(u=>{if(u.docChanged&&!ignore)options.onChange?.(u.state.doc.toString());if(u.selectionSet||u.docChanged)options.onSelection?.(u.state.selection.main.head,u.state.doc);})]})});
 return {view,setReviews(payload){const review=normalizeReviewFindings(payload,view.state.doc.toString(),view.state.readOnly);view.dispatch({effects:reviewEffect.of(review)});return !!review;},clearReviews(){view.dispatch({effects:reviewEffect.of(null)});},setProposal(proposal){if(!proposalMatches(proposal,view.state.doc.toString(),view.state.readOnly)){view.dispatch({effects:proposalEffect.of(null)});return false;}view.dispatch({effects:proposalEffect.of(proposal)});return true;},clearProposal(){view.dispatch({effects:proposalEffect.of(null)});},refreshLive(){if(live)view.dispatch({effects:liveRefreshEffect.of(null)});},complete:()=>startCompletion(view),getText:()=>view.state.doc.toString(),setText(text){text=normalizeEditorText(text);if(text===view.state.doc.toString())return;ignore=true;const old=view.state.doc.toString();let from=0,endOld=old.length,endNew=text.length;while(from<endOld&&from<endNew&&old[from]===text[from])from++;while(endOld>from&&endNew>from&&old[endOld-1]===text[endNew-1]){endOld--;endNew--;}view.dispatch({changes:{from,to:endOld,insert:text.slice(from,endNew)},annotations:isolateHistory.of('full')});ignore=false;},setReadOnly(value){view.dispatch({effects:readOnly.reconfigure(EditorState.readOnly.of(value))});},refresh(){const proposal=view.state.field(proposalField),review=view.state.field(reviewField),effects=[config.reconfigure(theme())];if(review)effects.push(reviewEffect.of(review),openReviewEffect.of(review.open));if(proposal)effects.push(proposalEffect.of(proposal),openProposalEffect.of(proposal.open));view.dispatch({effects});},focus(){view.focus();},select(position,length=0){const p=Math.max(0,Math.min(position,view.state.doc.length));view.dispatch({selection:{anchor:p,head:Math.min(p+length,view.state.doc.length)},effects:EditorView.scrollIntoView(p,{y:'center'})});view.focus();},undo(){return undo(view);},redo(){return redo(view);},destroy(){view.destroy();}};
}
