import {readProjectBuild} from './project-build.js';
import {organizeToolbar} from './toolbar.js';
import './updater.css';
import {createUpdater} from './updater.js';
import {invoke as nativeInvoke} from '@tauri-apps/api/core';
import {listen} from '@tauri-apps/api/event';
import {getCurrentWindow} from '@tauri-apps/api/window';
import {open as openDialog,save as saveDialog} from '@tauri-apps/plugin-dialog';
import {createEditor,normalizeEditorText} from './editor.js';
import {bindSplitter} from './splitter.js';
import {localizeError} from './errors-i18n.js';
import {mountStructure} from './structure.js';
import {openTestTransaction,createTestReporter} from './transactions.js';
import {mountAssistant} from './assistant.js';
import {showSettings} from './settings.js';
import './style.css';
import './structure.css';
import './assistant.css';
const $=s=>document.querySelector(s),el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const state={documents:[],current:null,root:null,entry:null,appName:'',settings:{language:'de',darkMode:false,wordWrap:false,aiHover:false,aiEnabled:false,model:'gpt-6-astra',reasoningEffort:'max',maxOutputTokens:32768,maxRequests:8},info:null,busy:false,build:null,view:'text',panels:{project:true,results:true,assistant:false},focus:null,diagnostics:[],files:[],cancelled:false};
const t=(de,en)=>state.settings.language==='en'?en:de;
const join=(...parts)=>parts.filter(Boolean).join('/').replace(/\\/g,'/').replace(/\/{2,}/g,'/');
const basename=p=>p?.split(/[\\/]/).pop()||'';
const norm=p=>state.info?.platform==='windows'?p.replace(/\\/g,'/').toLowerCase():p.replace(/\\/g,'/');
const same=(a,b)=>a&&b&&norm(a)===norm(b);
const sourceReadonly=p=>/\.sil$/i.test(p)||/(^|[\\/])build([\\/]|$)/i.test(p)||/^(artifact|manifest)\.json$/i.test(basename(p))||state.info&&norm(p).startsWith(norm(state.info.resources)+'/');
const invoke=async(command,args={})=>{try{return await (window.__ARGENT_TEST__?window.__ARGENT_TEST__.invoke(command,args):nativeInvoke(command,args));}catch(error){throw new Error(localizeError(error,state.settings.language));}};
let updater=null;
let statusMessage=null;
function notify(message){statusMessage=message;$('#status').textContent=String(typeof message==='function'?message():message);}
function fail(error){notify(()=>t('Fehler: ','Error: ')+localizeError(error,state.settings.language));return messageDialog(String(error.message||error),t('Fehler','Error'),['OK']);}
function messageDialog(text,title,choices){return new Promise(resolve=>{const d=el('dialog','message-dialog'),h=el('h3','',title),p=el('p','',text),buttons=el('div','dialog-buttons');const finish=value=>{d.close();d.remove();resolve(value);};choices.forEach(choice=>{const b=el('button','',choice);b.onclick=()=>finish(choice);buttons.append(b);});d.append(h,p,buttons);document.body.append(d);d.addEventListener('cancel',e=>{e.preventDefault();finish(null);});d.showModal();});}
function askName(title,initial){return new Promise(resolve=>{const d=el('dialog','message-dialog'),h=el('h3','',title),input=el('input'),buttons=el('div','dialog-buttons');input.value=initial;input.style.width='100%';const done=value=>{d.close();d.remove();resolve(value);};const ok=el('button','',t('Erstellen','Create'));ok.onclick=()=>{const name=input.value.trim();if(!name||/[\\/:*?"<>|]/.test(name)||name==='.'||name==='..'||/[. ]$/.test(name))return input.setCustomValidity(t('Ungültiger Name','Invalid name')),input.reportValidity();done(name);};const cancel=el('button','',t('Abbrechen','Cancel'));cancel.onclick=()=>done(null);input.oninput=()=>input.setCustomValidity('');input.onkeydown=e=>{if(e.key==='Enter')ok.click();};buttons.append(ok,cancel);d.append(h,input,buttons);document.body.append(d);d.addEventListener('cancel',()=>done(null));d.showModal();input.focus();input.select();});}
function toolbarButton(id,de,en,action){const b=el('button','toolbar-button',t(de,en));b.id=id;b.dataset.de=de;b.dataset.en=en;b.onclick=()=>Promise.resolve(action()).catch(fail);return b;}
async function prepareUpdate(){
 if(state.busy||assistant?.isBusy()){notify(()=>t('Bitte den laufenden Vorgang zuerst abschließen.','Please finish the current operation first.'));return false;}
 state.busy=true;sync();let unlocked=false;const unlock=()=>{if(!unlocked){unlocked=true;state.busy=false;sync();}};
 try{if(!await saveCurrent()){unlock();return false;}return unlock;}catch(error){unlock();throw error;}
}
function renderShell(){const app=$('#app');app.innerHTML='';const toolbar=el('div','toolbar main-toolbar');const brand=el('img','brand');brand.src=new URL('../resources/assets/argent-studio.svg',import.meta.url).href;brand.alt='';const identity=el('div','brand-identity'),brandText=el('div','brand-text'),credit=el('span','brand-credit','powered by '),creditName=el('span','brand-credit-name');creditName.append(el('span','brand-kas','Kas'),el('span','brand-btc','BTC'));credit.append(creditName);brandText.append(el('span','brand-name','Argent Studio'),credit);identity.append(brand,brandText);toolbar.append(identity);toolbar.append(toolbarButton('check-updates','Updates','Updates',()=>updater?.checkForUpdates({manual:true})));
 toolbar.append(toolbarButton('new-project','Neues Projekt','New project',newProject),toolbarButton('open-project','Projekt öffnen','Open project',chooseProject),toolbarButton('duplicate-project','Projekt duplizieren …','Duplicate project …',duplicateProject));
 const examples=el('details','examples-menu'),summary=el('summary','toolbar-button',t('Beispiele','Examples')),menu=el('div','popup-menu');summary.dataset.de='Beispiele';summary.dataset.en='Examples';for(const [id,de,en]of [['tickets','Tickets – Einstieg','Tickets – introduction'],['spawns','Spawns – Covenants erzeugen','Spawns – create covenants'],['stones','Stones – mehrere Akteure','Stones – multiple actors'],['icc','ICC – Kommunikation zwischen Apps','ICC – communication between apps']])menu.append(toolbarButton('example-'+id,de,en,async()=>{examples.open=false;await loadExample(id);}));examples.append(summary,menu);toolbar.append(examples);
 for(const [id,de,en,fn]of [['new-file','Neue Datei','New file',newFile],['save','Alle speichern','Save all',saveCurrent],['close','Datei schließen','Close file',()=>closeDocument(state.current)],['compile','▶ Kompilieren','▶ Compile',build],['cancel','■ Build abbrechen','■ Cancel build',cancelBuild],['inspect','Build-Bericht','Build report',inspectBuild],['compiler','Compiler wählen','Select compiler',chooseCompiler],['settings','Einstellungen','Settings',()=>showSettings(context)],['help','Hilfe','Help',()=>openFile(join(state.info.resources,state.settings.language==='en'?'README.en.md':'README.md'))]])toolbar.append(toolbarButton(id,de,en,fn));
 const buildbar=el('div','toolbar buildbar');buildbar.append(toolbarButton('set-entry','Aktive Datei als Build-Datei','Use active file as entry',()=>setBuildEntry(state.current?.path)));const entry=el('span','entry-label',t('Keine Build-Datei','No build entry'));entry.id='entry-label';const appLabel=el('label','app-label',t('App (optional):','App (optional):')),appInput=el('input');appInput.id='app-name';appInput.setAttribute('aria-label','App (optional)');appInput.oninput=()=>{state.appName=appInput.value;invalidateBuild();};buildbar.append(entry,el('span','separator'),appLabel,appInput);
 const views=el('div','toolbar viewbar');for(const [id,de,en,fn]of [['view-text','Text','Text',()=>setView('text')],['view-structure','Struktur','Structure',()=>setView('structure')],['panel-project','Projekt','Project',()=>togglePanel('project')],['panel-results','Build / Ergebnisse','Build / results',()=>togglePanel('results')],['panel-assistant','KI-Assistent','AI assistant',()=>togglePanel('assistant')],['focus','Fokusmodus','Focus mode',toggleFocus],['test-transaction','Testtransaktion','Test transaction',()=>openTestTransaction(context)]])views.append(toolbarButton(id,de,en,fn));
 const workspace=el('main','workspace');workspace.id='workspace';const project=el('aside','project-pane');project.id='project-pane';project.append(el('div','pane-heading','PROJEKT'));const tree=el('div','project-tree');tree.id='project-tree';project.append(tree);const leftSplitter=el('div','splitter vertical');const center=el('div','center-pane');center.id='center-pane';const editorArea=el('section','editor-area'),tabs=el('div','document-tabs');tabs.id='document-tabs';const hosts=el('div','editor-hosts');hosts.id='editor-hosts';editorArea.append(tabs,hosts);const horizontal=el('div','splitter horizontal');horizontal.id='result-splitter';const results=el('section','results-pane');results.id='results-pane';const resultTabs=el('div','result-tabs');for(const [id,de,en]of [['output','Build-Ausgabe','Build output'],['errors','Fehler','Errors'],['artifacts','Erzeugte Dateien','Generated files']])resultTabs.append(toolbarButton('result-'+id,de,en,()=>selectResult(id)));resultTabs.append(toolbarButton('cleanup-builds','Builds bereinigen …','Clean up builds …',cleanupBuilds));const output=el('pre','result-content build-log');output.id='build-output';const errors=el('div','result-content');errors.id='build-errors';const artifacts=el('div','result-content artifact-tree');artifacts.id='build-artifacts';results.append(resultTabs,output,errors,artifacts);center.append(editorArea,horizontal,results);const rightSplitter=el('div','splitter vertical');rightSplitter.id='assistant-splitter';const assistantPane=el('aside','assistant-pane');assistantPane.id='assistant-pane';workspace.append(project,leftSplitter,center,rightSplitter,assistantPane);const statusbar=el('footer','statusbar'),status=el('span','',t('Initialisierung …','Initializing …'));status.id='status';const caret=el('span');caret.id='caret';statusbar.append(status,caret);app.append(toolbar,buildbar,views,workspace,statusbar);organizeToolbar(toolbar,buildbar,views,state.settings.language);selectResult('output');
 leftSplitter.id='project-splitter';
 bindSplitter(leftSplitter,{axis:'x',label:'Projektbreite / Project width',getSize:()=>project.getBoundingClientRect().width,setSize:n=>workspace.style.setProperty('--project-width',n+'px'),min:()=>120,max:()=>workspace.clientWidth-(state.panels.assistant?assistantPane.getBoundingClientRect().width+5:0)-305});
 bindSplitter(rightSplitter,{axis:'x',direction:-1,label:'KI-Breite / AI assistant width',getSize:()=>assistantPane.getBoundingClientRect().width,setSize:n=>workspace.style.setProperty('--assistant-width',n+'px'),min:()=>200,max:()=>workspace.clientWidth-(state.panels.project?project.getBoundingClientRect().width+5:0)-305});
 bindSplitter(horizontal,{axis:'y',direction:-1,label:'Höhe der Build-Ausgabe / Build output height',getSize:()=>results.getBoundingClientRect().height,setSize:n=>center.style.setProperty('--result-height',n+'px'),min:()=>90,max:()=>center.clientHeight-155});
}
let assistant,lastVisibleTab;
const context={invoke,getDocument:()=>state.current,getDocuments:()=>state.documents,getProjectRoot:()=>state.root,getSettings:()=>state.settings,setSettings:async settings=>{await invoke('save_settings',{settings});state.settings=settings;applySettings();},getBuild:()=>state.build,getBuildFiles:()=>state.build?.files||[],readBuildFile:async(path,offset=0)=>{if(!state.build)throw Error(t('Kein Build','No build'));const full=path.startsWith(state.build.output)?path:join(state.build.output,path);if(!norm(full).startsWith(norm(state.build.output)+'/')||path.includes('..'))throw Error(t('Ungültiger Build-Pfad','Invalid build path'));return (await invoke('read_ai_file',{projectRoot:state.root,path:norm(full).slice(norm(state.root).length+1),allowMissing:false})).slice(Number(offset),Number(offset)+160000);},openFile,updateDocument,build,notify,listFiles:async()=>state.files.filter(f=>!f.isDirectory&&!sourceReadonly(f.path)&&/\.ag$/i.test(f.path)).map(f=>f.path.slice(state.root.length+1)),loadExample,setBuildEntry,cancelBuild,openDialog,saveDialog,undo:path=>{const d=findDoc(path);return d&&(sharedHistory(d.path,false)||d.editor.undo());},redo:path=>{const d=findDoc(path);return d&&(sharedHistory(d.path,true)||d.editor.redo());},createEditor:(host,opts)=>createEditor(host,{...opts,getSettings:()=>state.settings})};
function sharedHistory(path,redo){for(const d of [...state.documents].reverse())if(d.structure?.trySharedHistory(path,redo))return true;return false;}
function findDoc(path){return path?state.documents.find(d=>same(d.path,path)):state.current;}
const reporter=createTestReporter({getNodes:()=>[...new Map(state.documents.flatMap(d=>d.structure?.getModel()?.nodes||[]).map(n=>[n.id,n])).values()],getDocuments:()=>state.documents,onChange:()=>state.current?.structure?.refresh()});
context.getTestBadge=reporter.getTestBadge;context.reportTest=reporter.reportTest;context.isBusy=()=>state.busy;context.isReadOnly=path=>!!sourceReadonly(path);
function sync(){if(!state.settings.aiEnabled){state.panels.assistant=false;if(state.focus)state.focus.assistant=false;}$('#panel-assistant').disabled=!state.settings.aiEnabled;for(const [key,value]of Object.entries(state.panels)){$('#'+key+'-pane')?.classList.toggle('is-hidden',!value);$('#panel-'+key).classList.toggle('checked',value);}$('#workspace').classList.toggle('no-project',!state.panels.project);$('#workspace').classList.toggle('no-assistant',!state.panels.assistant);$('#result-splitter').hidden=!state.panels.results;$('#focus').classList.toggle('checked',!!state.focus);const structural=state.view==='structure'&&state.current&&!state.current.generated&&/\.ag$/i.test(state.current.path);$('#view-structure').disabled=false;$('#view-structure').classList.toggle('checked',!!structural);$('#view-text').classList.toggle('checked',!structural);$('#test-transaction').hidden=!structural;$('#test-transaction').disabled=state.busy;$('#cancel').disabled=!state.busy;$('#compile').disabled=state.busy;$('#inspect').disabled=state.busy||!state.build?.success;$('#app-name').disabled=state.busy;$('#duplicate-project').disabled=state.busy||!state.root;$('#cleanup-builds').disabled=state.busy||!state.root;$('#entry-label').textContent=basename(state.entry)||t('Keine Build-Datei','No build entry');for(const id of ['new-project','open-project','new-file','close','compiler','set-entry'])$('#'+id).disabled=state.busy;for(const d of state.documents){d.host.hidden=d!==state.current;d.tab.classList.toggle('active',d===state.current);d.editor.setReadOnly(d.generated||state.busy);d.codeHost.hidden=d===state.current&&!!structural;d.structureHost.hidden=d!==state.current||!structural;}if(structural&&!state.current.structure){const owner=state.current;owner.structure=mountStructure(owner.structureHost,{...context,getDocument:()=>owner});}renderCaptions();if(state.current?.tab!==lastVisibleTab){lastVisibleTab=state.current?.tab;lastVisibleTab?.scrollIntoView({block:'nearest',inline:'nearest'});}}
function renderCaptions(){for(const d of state.documents)d.tab.querySelector('span').textContent=basename(d.path)+(d.bytes!=null?' ('+d.bytes+' Bytes)':'')+(d.generated&&d.bytes==null?t(' [Ansicht]',' [Read only]'):d.text!==normalizeEditorText(d.diskText)?' *':'');for(const row of document.querySelectorAll('.file-row')){const selected=!!same(state.current?.path,row.dataset.path);row.classList.toggle('selected',selected);row.setAttribute('aria-current',String(selected));}}
async function setView(mode){if(mode==='structure'&&(!state.current||state.current.generated||!/\.ag$/i.test(state.current.path))){const path=state.entry||state.documents.find(d=>!d.generated&&/\.ag$/i.test(d.path))?.path||state.files.find(f=>!f.isDirectory&&/\.ag$/i.test(f.path)&&!sourceReadonly(f.path))?.path;if(path)await openFile(path);else{notify(()=>t('Dieses Projekt enthält noch keine Argent-Quelldatei für die Strukturansicht.','This project has no Argent source file for the structure view yet.'));return;}}state.view=mode;sync();if(mode==='structure')state.current?.structure?.refresh();}
function togglePanel(key){if(key==='assistant'&&!state.settings.aiEnabled)return;state.panels[key]=!state.panels[key];state.focus=null;sync();}
function toggleFocus(){if(state.focus){state.panels=state.focus;state.focus=null;}else{state.focus={...state.panels};state.panels={project:false,results:false,assistant:false};}sync();}
function invalidateBuild(){if(state.build)state.build.stale=true;}
function changed(doc,text){doc.text=text;invalidateBuild();renderCaptions();}
async function language(doc,position,mode){const r=await invoke('language_request',{request:{path:doc.path,text:doc.text,position,documents:state.documents.map(d=>({path:d.path,text:d.text}))}});if(mode==='hover'){const start=doc.text.slice(0,position).match(/[\w]+$/)?.[0]||'',end=doc.text.slice(position).match(/^[\w]+/)?.[0]||'';return r.items?.find(x=>x.name===start+end)||{};}return r;}
async function definition(doc,position){const a=doc.text.slice(0,position).match(/[\w]+$/)?.[0]||'',b=doc.text.slice(position).match(/^[\w]+/)?.[0]||'';const r=await language(doc,position);const item=r.items?.find(x=>x.name===a+b&&x.path&&x.position>=0);if(item)await openFile(item.path,{position:item.position});else notify(()=>t('Keine Definition gefunden.','No definition found.'));}
async function openFile(path,location){if(!path)return;let doc=findDoc(path);if(!doc){const text=await invoke('read_file',{path});doc=addDocument(path,text,sourceReadonly(path));}state.current=doc;sync();if(location!==undefined){setView('text');let position=typeof location==='number'?location:location.position??0;if(location.line){const lines=doc.text.split('\n');position=lines.slice(0,location.line-1).reduce((n,s)=>n+s.length+1,0)+(location.column?Array.from(lines[location.line-1]||'').slice(0,location.column-1).join('').length:0);}doc.editor.select(position,location.length||0);}return doc;}
function addDocument(path,text,generated=false,diskText=text){text=normalizeEditorText(text);const doc={path,text,diskText,generated};const host=el('div','document-host'),codeHost=el('div','code-host'),structureHost=el('div','structure-host'),tab=el('button','document-tab'+(generated?' generated':''));tab.title=path;const label=el('span'),close=el('b','','×');tab.append(label,close);tab.onclick=()=>{state.current=doc;sync();};close.onclick=e=>{e.stopPropagation();closeDocument(doc).catch(fail);};tab.draggable=true;tab.ondragstart=e=>e.dataTransfer.setData('text/plain',path);tab.ondragover=e=>e.preventDefault();tab.ondrop=e=>{e.preventDefault();const other=findDoc(e.dataTransfer.getData('text/plain'));if(!other||other===doc)return;const index=state.documents.indexOf(doc);state.documents.splice(state.documents.indexOf(other),1);state.documents.splice(index,0,other);$('#document-tabs').replaceChildren(...state.documents.map(d=>d.tab));};host.append(codeHost,structureHost);$('#editor-hosts').append(host);$('#document-tabs').append(tab);Object.assign(doc,{host,codeHost,structureHost,tab});doc.editor=createEditor(codeHost,{text,readOnly:generated,getSettings:()=>state.settings,history:redo=>sharedHistory(doc.path,redo),canShare:()=>assistant?.isSharing(),aiExplain:pos=>explainSymbol(doc,pos),onChange:value=>changed(doc,value),onSelection:(pos,document)=>{if(state.current!==doc)return;const line=document.lineAt(pos);$('#caret').textContent=t('Zeile ','Line ')+line.number+t(' · Spalte ',' · Column ')+(pos-line.from+1);},language:/\.ag$/i.test(path)?(pos,mode)=>language(doc,pos,mode):null,definition:pos=>definition(doc,pos)});codeHost.oncontextmenu=e=>{e.preventDefault();showEditorMenu(e,doc);};state.documents.push(doc);return doc;}
function updateDocument(path,text){text=normalizeEditorText(text);let doc=findDoc(path);const created=!doc;const baseline=state.documents.flatMap(d=>d.structure?.getModel()?.sources||[]).find(d=>same(d.path,path));if(!doc)doc=addDocument(path,text,sourceReadonly(path),baseline?.text??null);if(doc.generated||state.busy)throw Error(t('Datei ist schreibgeschützt.','File is read only.'));doc.editor.setText(text);changed(doc,text);if(created&&!baseline){state.current=doc;sync();}return doc;}
// Keep each document's writes ordered and retain the exact successfully written snapshot.
function saveDocument(doc){
 if(!doc||doc.generated)return Promise.resolve(true);
 const pending=(doc.savePending||Promise.resolve()).catch(()=>{}).then(async()=>{
  if(doc.text===normalizeEditorText(doc.diskText))return true;
  let disk=null;
  try{disk=await invoke('read_file',{path:doc.path});}catch(e){if(!/not found|cannot find|os error 2|does not exist/i.test(String(e)))throw e;}
  if(disk!==doc.diskText&&disk!==null){
   const answer=await messageDialog(t('Die Datei wurde außerhalb des Editors geändert. Mit dem Editorinhalt überschreiben?\n','The file was changed outside the editor. Overwrite?\n')+doc.path,t('Dateikonflikt','File conflict'),[t('Ja','Yes'),t('Nein','No')]);
   if(answer!==t('Ja','Yes'))return false;
  }
  const writtenText=doc.text;
  await invoke('write_file',{path:doc.path,text:writtenText});
  doc.diskText=writtenText;renderCaptions();notify(()=>t('Gespeichert: ','Saved: ')+doc.path);return true;
 });
 doc.savePending=pending;
 const clear=()=>{if(doc.savePending===pending)doc.savePending=null;};pending.then(clear,clear);
 return pending;
}
async function saveCurrent(){for(const doc of [...state.documents])if(!await saveDocument(doc))return false;await refreshFiles();return state.documents.every(d=>d.generated||d.text===normalizeEditorText(d.diskText));}
async function confirmDocument(doc){
 while(doc.savePending)await doc.savePending;
 if(doc.generated||doc.text===normalizeEditorText(doc.diskText))return true;
 const answer=await messageDialog(t('Änderungen speichern?\n','Save changes?\n')+basename(doc.path),t('Ungespeicherte Änderungen','Unsaved changes'),[t('Speichern','Save'),t('Verwerfen','Discard'),t('Abbrechen','Cancel')]);
 if(answer===t('Verwerfen','Discard'))return true;
 if(answer!==t('Speichern','Save')||!await saveDocument(doc))return false;
 while(doc.savePending)await doc.savePending;
 return doc.text===normalizeEditorText(doc.diskText);
}
async function confirmAll(){if(state.busy||assistant?.isBusy())return false;const confirmed=new Map();for(const d of state.documents){if(!await confirmDocument(d))return false;confirmed.set(d,d.text);}return state.documents.every(d=>confirmed.has(d)&&confirmed.get(d)===d.text&&!d.savePending);}
async function closeDocument(doc){if(!doc||state.busy||assistant?.isBusy()||!await confirmDocument(doc)||!state.documents.includes(doc))return;doc.structure?.dispose();doc.editor.destroy();doc.host.remove();doc.tab.remove();state.documents.splice(state.documents.indexOf(doc),1);if(state.current===doc)state.current=state.documents.at(-1)||null;sync();}
let projectLoadId=0;
async function loadProject(root){if(state.busy)return;const loadId=++projectLoadId;for(const d of state.documents){d.structure?.dispose();d.editor.destroy();d.host.remove();d.tab.remove();}state.documents=[];state.current=null;state.root=root;state.entry=null;state.build=null;state.diagnostics=[];state.cancelled=false;state.files=[];$('#build-output').textContent='';$('#build-artifacts').replaceChildren();renderErrors();reporter.invalidate();selectResult('output');state.appName='';$('#app-name').value='';assistant?.projectChanged();await refreshFiles();const first=state.files.find(f=>!f.isDirectory&&/\.ag$/i.test(f.path)&&!sourceReadonly(f.path));if(first){state.entry=first.path;await openFile(first.path);}sync();try{const restored=await readProjectBuild(root,invoke);if(loadId!==projectLoadId||state.busy||state.build||!restored)return;state.build=restored;$('#build-output').textContent=restored.stdout;await renderArtifacts(restored);selectResult('artifacts');sync();}catch(e){if(loadId===projectLoadId)notify(()=>t('Build-Dateien konnten nicht geladen werden: ','Could not load build files: ')+e);}}
async function chooseProject(){if(!await confirmAll())return;const root=await openDialog({directory:true,multiple:false,defaultPath:state.info.projectsDir,title:t('Projekt öffnen','Open project')});if(root)await loadProject(root);}
async function duplicateProject(){if(!state.root||!await confirmAll()||!await saveCurrent())return;const name=await askName(t('Projekt duplizieren','Duplicate project'),basename(state.root)+t('-Kopie','-copy'));if(!name)return;const result=await invoke('duplicate_project',{projectRoot:state.root,name});await loadProject(result.root);}
async function cleanupBuilds(){if(!state.root||state.busy)return;const answer=await messageDialog(t('Die letzten fünf Builds bleiben erhalten. Ältere Builds werden in den Projektpapierkorb verschoben.','The last five builds are kept. Older builds are moved to the project trash.'),t('Builds bereinigen','Clean up builds'),[t('Bereinigen','Clean up'),t('Abbrechen','Cancel')]);if(answer!==t('Bereinigen','Clean up'))return;const result=await invoke('cleanup_builds',{projectRoot:state.root});notify(()=>t('Archivierte Builds: ','Archived builds: ')+result.moved);await refreshFiles();}
async function newProject(){if(!await confirmAll())return;const name=await askName(t('Leeres Projekt erstellen','Create empty project'),t('MeinProjekt','MyProject'));if(!name)return;const path=join(state.info.projectsDir||join(state.info.dataDir,'projects'),name);await invoke('create_directory',{path});await loadProject(path);}
async function newFile(){if(!state.root||state.busy)return;const path=await saveDialog({defaultPath:join(state.root,'contract.ag'),filters:[{name:'Argent',extensions:['ag']}]});if(!path)return;try{await openFile(path);return;}catch(e){if(!/not found|cannot find|os error 2|does not exist/i.test(String(e)))throw e;}await invoke('create_file',{path,text:t('// Neue Argent-Anwendung\n','// New Argent application\n')});await refreshFiles();await openFile(path);}
async function loadExample(id){if(!await confirmAll())return;const result=await invoke('open_example',{id});await loadProject(result.root||result.path);setBuildEntry(result.entry,result.app);await openFile(result.entry);notify(()=>t('Beispielprojekt: ','Example project: ')+state.root);return result;}
function setBuildEntry(path,app){if(!path||sourceReadonly(path)||!/\.ag$/i.test(path))throw Error(t('Bitte eine .ag-Quelldatei auswählen.','Select an .ag source file.'));state.entry=path;if(app!==undefined){state.appName=app;$('#app-name').value=app;}invalidateBuild();sync();}
async function chooseCompiler(){const path=await openDialog({multiple:false,title:t('Vorhandenen Argent-Compiler verbinden','Connect an existing Argent compiler')});if(path){state.settings.compiler=path;await invoke('save_settings',{settings:state.settings});state.info.compiler=path;notify(()=>t('Compiler bereit: ','Compiler ready: ')+path);}}
function fileRow(path,{bytes,generated=false}={}){
 const name=basename(path),extension=name.includes('.')?name.split('.').pop().toLowerCase():'file';
 const row=el('button','tree-file file-row');row.type='button';row.dataset.path=path;row.title=path;
 const icon=el('span','file-kind kind-'+extension,({ag:'AG',sil:'SIL',json:'{}',md:'M',file:'≡'})[extension]||'≡');icon.setAttribute('aria-hidden','true');
 row.append(icon,el('span','file-name',name));
 if(bytes!=null){const badge=el('span','file-size',bytes+' Bytes');badge.title=t('Kompilierte Bytecode-Vorlage','Compiled bytecode template');row.append(badge);}
 row.classList.toggle('selected',same(state.current?.path,path));row.setAttribute('aria-current',same(state.current?.path,path)?'true':'false');
 row.onclick=async()=>{try{const doc=await openFile(path);if(generated){doc.generated=true;doc.bytes=bytes;sync();}}catch(e){fail(e);}};
 return row;
}
async function refreshFiles(){
 if(!state.root)return;state.files=[];const tree=$('#project-tree');
 const prior=new Map([...tree.querySelectorAll('details[data-folder]')].map(d=>[d.dataset.folder,d.open]));
 tree.replaceChildren();const name=basename(state.root),cleanName=name.replace(/^(tickets|spawns|stones|icc)-\d{10,}$/i,'$1');
 const rootRow=el('div','tree-root project-root');rootRow.title=state.root;
 rootRow.append(el('span','folder-icon','▱'),el('span','project-name',cleanName));tree.append(rootRow);
 async function walk(path,parent,depth){if(depth>12)return;const entries=await invoke('list_directory',{path});
  for(const file of entries){if(file.name.startsWith('.')||['target','node_modules','build'].includes(file.name))continue;state.files.push(file);
   if(file.isDirectory){const details=el('details','tree-directory'),s=el('summary','folder-row',file.name);details.dataset.folder=file.path;details.open=prior.get(file.path)??(depth<1&&file.name!=='build');details.append(s);parent.append(details);
    if(file.name==='build'){let loaded=false;details.addEventListener('toggle',async()=>{if(details.open&&!loaded){loaded=true;try{await walk(file.path,details,depth+1);}catch(e){loaded=false;notify(String(e));}}});if(details.open){loaded=true;await walk(file.path,details,depth+1);}}
    else await walk(file.path,details,depth+1);
   }else{const row=fileRow(file.path);row.oncontextmenu=e=>{e.preventDefault();showFileMenu(e,file.path);};parent.append(row);}
  }
 }
 await walk(state.root,tree,0);
}
function popup(x,y,items){document.querySelector('.context-menu')?.remove();const menu=el('div','context-menu');menu.style.left=Math.min(x,window.innerWidth-250)+'px';menu.style.top=Math.min(y,window.innerHeight-250)+'px';for(const [label,fn]of items){const b=el('button','',label);b.onclick=()=>{menu.remove();Promise.resolve(fn()).catch(fail);};menu.append(b);}document.body.append(menu);setTimeout(()=>document.addEventListener('pointerdown',e=>{if(!menu.contains(e.target))menu.remove();},{once:true}),0);}
function showFileMenu(e,path){popup(e.clientX,e.clientY,[[t('Neue Datei …','New file …'),newFile],[t('Datei löschen …','Delete file …'),async()=>{if(state.busy||sourceReadonly(path))return;const result=await messageDialog(t('Datei in den Projektpapierkorb verschieben?\n','Move file to project trash?\n')+path,t('Datei löschen','Delete file'),[t('Ja','Yes'),t('Nein','No')]);if(result!==t('Ja','Yes'))return;const doc=findDoc(path);if(doc&&!await confirmDocument(doc))return;await invoke('trash_file',{path,projectRoot:state.root});if(doc){doc.diskText=doc.text;await closeDocument(doc);}if(same(state.entry,path))state.entry=null;await refreshFiles();sync();}]]);}
function explainSymbol(doc,pos){if(!assistant?.isSharing())return notify(()=>t('Bitte Projektcode für KI freigeben.','Allow AI access to project code first.'));const symbol=(doc.text.slice(0,pos).match(/\w+$/)?.[0]||'')+(doc.text.slice(pos).match(/^\w+/)?.[0]||'');return assistant.explain(t('Erkläre das Symbol ','Explain the symbol ')+symbol+t(' in der aktiven Datei.',' in the active file.'));}
function showEditorMenu(e,doc){popup(e.clientX,e.clientY,[[t('Vorschläge · Strg+Leertaste','Suggestions · Ctrl+Space'),()=>doc.editor.complete()],[t('Definition öffnen · F12','Go to definition · F12'),()=>definition(doc,doc.editor.view.state.selection.main.head)],[t('Rückgängig','Undo'),()=>doc.editor.undo()],[t('Wiederherstellen','Redo'),()=>doc.editor.redo()],[t('Auswahl kopieren','Copy selection'),()=>navigator.clipboard.writeText(doc.editor.view.state.sliceDoc(doc.editor.view.state.selection.main.from,doc.editor.view.state.selection.main.to))],[t('KI: Auswahl erklären','AI: explain selection'),()=>assistant.explain(t('Erkläre diese Auswahl:\n','Explain this selection:\n')+doc.editor.view.state.sliceDoc(doc.editor.view.state.selection.main.from,doc.editor.view.state.selection.main.to))]]);}
function selectResult(id){for(const k of ['output','errors','artifacts']){$('#build-'+k).hidden=k!==id;$('#result-'+k).classList.toggle('checked',k===id);}}
function appendLog(line){const output=$('#build-output');if(output.textContent.length<2000000)output.textContent+=line+'\n';output.scrollTop=output.scrollHeight;const cleaned=line.replace(/\x1B\[[0-?]*[ -/]*[@-~]/g,'').replace(/^argentc: /,'');const m=cleaned.match(/^(?:(.+):)?(\d+):(\d+):\s*(.*)$/);if(m){let path=m[1]||state.entry;if(path.startsWith('\\\\?\\'))path=path.slice(4);if(!/^(?:[A-Za-z]:|\/)/.test(path))path=join(state.root,path);state.diagnostics.push({path,line:+m[2],column:+m[3],message:m[4]});renderErrors();}}
function renderErrors(){const host=$('#build-errors');host.replaceChildren();const table=el('table','diagnostics');const head=el('tr');[t('Datei','File'),t('Zeile','Line'),t('Spalte','Column'),t('Meldung','Message')].forEach(s=>head.append(el('th','',s)));table.append(head);for(const d of state.diagnostics){const row=el('tr');[d.path,d.line,d.column,d.message].forEach(s=>row.append(el('td','',s)));row.ondblclick=()=>openFile(d.path,{line:d.line,column:d.column}).catch(fail);table.append(row);}host.append(table);}
function bytecodeSizes(artifact){const sizes={};for(const [name,c]of Object.entries(artifact?.sil_abi?.contracts||{})){const data=c.compiled?.bytecode;const key=basename(c.source_path||name).replace(/\.sil$/i,'');if(Array.isArray(data)&&data.every(n=>Number.isInteger(n)&&n>=0&&n<=255))sizes[key]=data.length;}return sizes;}
async function renderArtifacts(result){
 const host=$('#build-artifacts'),header=el('div','artifact-status '+(result.success?'succeeded':'failed'));
 header.append(el('span','status-dot',result.success?'✓':'!'),el('span','',result.restored?t('Gespeicherter Build · vor Testtransaktionen neu kompilieren','Saved build · rebuild before test transactions'):result.success?t('Build erfolgreich','Build succeeded'):t('Build unvollständig','Incomplete build')));header.title=result.output;host.replaceChildren(header);
 const sizes=bytecodeSizes(result.artifact),paths=(result.files||[]).map(f=>typeof f==='string'?f:f.path);
 for(const [label,files]of [[t('VERTRÄGE','CONTRACTS'),paths.filter(p=>/\.sil$/i.test(p))],[t('BUILD-DATEIEN','BUILD FILES'),paths.filter(p=>!/\.sil$/i.test(p))]]){
  if(!files.length)continue;const group=el('section','artifact-group');group.append(el('div','file-group-label',label));
  for(const path of files)group.append(fileRow(path,{bytes:sizes[basename(path).replace(/\.sil$/i,'')],generated:true}));host.append(group);
 }
 return sizes;
}
async function build(){if(state.busy)return state.build;if(!state.entry){notify(()=>t('Bitte eine .ag-Datei als Build-Datei wählen.','Select an .ag build entry.'));return null;}if(!await saveCurrent())return null;state.busy=true;++projectLoadId;state.cancelled=false;state.build=null;state.diagnostics=[];$('#build-artifacts').replaceChildren();$('#build-output').textContent='';renderErrors();selectResult('output');sync();notify(()=>t('Kompilierung läuft …','Compiling …'));const snapshot=state.documents.map(d=>({path:d.path,text:d.text}));try{const result=await invoke('build',{entry:state.entry,projectRoot:state.root,appName:state.appName,compiler:state.settings.compiler||null});if(!$('#build-output').textContent.trim()){appendLog(result.stdout||'');if(result.stderr)appendLog(result.stderr);}result.stale=false;result.sources=snapshot;result.diagnostics=[...state.diagnostics];state.build=result;reporter.invalidate();result.artifactPath=join(result.output,'artifact.json');if(result.success){result.artifact=JSON.parse(await invoke('read_file',{path:result.artifactPath}));state.build=result;}const sizes=await renderArtifacts(result);const status=()=>state.cancelled?t('Build abgebrochen.','Build cancelled.'):result.success?t('Build erfolgreich','Build succeeded')+Object.entries(sizes).map(([name,n])=>' · '+name+': '+n+' Bytes').join(''):t('Build fehlgeschlagen · Exitcode ','Build failed · Exit code ')+result.exitCode;appendLog(status());notify(status);await invoke('write_file',{path:join(result.output,'editor-build.log'),text:$('#build-output').textContent}).catch(()=>{});selectResult(result.success?'artifacts':state.diagnostics.length?'errors':'output');return result;}catch(e){appendLog(String(e));notify(()=>t('Build konnte nicht abgeschlossen werden: ','Build could not complete: ')+e);throw e;}finally{state.busy=false;sync();}}
async function cancelBuild(){state.cancelled=true;await invoke('cancel_operation');notify(()=>t('Abbruch angefordert.','Cancellation requested.'));}
async function inspectBuild(){if(!state.build||state.busy)return;state.busy=true;sync();selectResult('output');try{const r=await invoke('inspect',{output:state.build.output,compiler:state.settings.compiler||null});appendLog(r.stdout||'');if(r.stderr)appendLog(r.stderr);notify(()=>t('Build-Bericht · Exitcode ','Build report · Exit code ')+r.exitCode);}finally{state.busy=false;sync();}}
function applySettings(){document.querySelector('.pane-heading').textContent=t('PROJEKT','PROJECT');document.documentElement.dataset.theme=state.settings.darkMode?'dark':'light';document.body.classList.toggle('dark',!!state.settings.darkMode);for(const e of document.querySelectorAll('[data-de]'))e.textContent=state.settings.language==='en'?e.dataset.en:e.dataset.de;for(const [id,de,en]of [['project-splitter','Projektbreite','Project width'],['assistant-splitter','KI-Breite','AI assistant width'],['result-splitter','Höhe der Build-Ausgabe','Build output height']]){const node=$('#'+id);node.title=t(de,en);node.setAttribute('aria-label',t(de,en));}for(const d of state.documents){d.editor.refresh();d.structure?.refreshSettings();}assistant?.refresh();renderErrors();if(state.build)renderArtifacts(state.build);if(statusMessage!==null)notify(statusMessage);const selection=state.current?.editor.view.state.selection.main;if(selection){const line=state.current.editor.view.state.doc.lineAt(selection.head);$('#caret').textContent=t('Zeile ','Line ')+line.number+t(' · Spalte ',' · Column ')+(selection.head-line.from+1);}sync();}
let appExitPending=false;
async function confirmAppExit(){if(appExitPending)return;appExitPending=true;try{if(await confirmAll())await invoke('confirm_exit');}finally{appExitPending=false;}}
async function start(){renderShell();assistant=mountAssistant($('#assistant-pane'),context);try{state.info=await invoke('app_info');state.settings={...state.settings,...await invoke('load_settings')};applySettings();if(!window.__ARGENT_TEST__){await listen('process-output',e=>appendLog(e.payload.line));if(state.info.platform==='macos'){await listen('exit-requested',()=>{void confirmAppExit().catch(fail);});await invoke('exit_handler_ready');}getCurrentWindow().onCloseRequested(async e=>{e.preventDefault();if(await confirmAll())await getCurrentWindow().destroy();});}const examples=state.info.defaultProject||await invoke('clone_example',{id:'tickets'});await loadProject(examples.root||examples.path);setBuildEntry(examples.entry,examples.app);notify(()=>state.info.compiler?t('Compiler bereit: ','Compiler ready: ')+state.info.compiler:t('Compiler fehlt · Editor bereit.','Compiler missing · Editor ready.'));}catch(e){notify(String(e));console.error(e);}sync();updater=createUpdater({getSettings:()=>state.settings,isSupported:()=>!!state.info?.updatesEnabled,prepareUpdate});if(state.info?.updatesEnabled)void updater.checkForUpdates();window.__ARGENT_APP__={state,context,openFile,build,setView,saveCurrent,loadExample,loadProject,applySettings,assistant};}
document.addEventListener('keydown',e=>{if(e.target.closest('dialog'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveCurrent().catch(fail);}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='o'){e.preventDefault();chooseProject().catch(fail);}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='w'){e.preventDefault();closeDocument(state.current).catch(fail);}else if(e.key==='F5'){e.preventDefault();build().catch(fail);}});
start();
