import {localizeError} from './errors-i18n.js';
import {el,addUsage,usageSummary} from './assistant.js';
export async function showSettings(context){
 const settings={...context.getSettings()},t=(de,en)=>settings.language==='en'?en:de;
 const dialog=el('dialog',{class:'settings-dialog','aria-label':t('Einstellungen','Settings')}),shell=el('div',{class:'settings-shell'}),tabs=el('div',{class:'settings-tabs',role:'tablist'}),pages=el('div',{class:'settings-pages'});dialog.dataset.dark=String(!!settings.darkMode);let active=true,apiChanged=false,adminChanged=false;const requests=new Set();
 const invoke=(name,args={})=>context.invoke(name,args),feedback=el('div',{class:'settings-feedback',role:'status'}),adminFeedback=el('div',{class:'settings-feedback',role:'status'}),usageLabel=el('p',{},usageSummary(settings.language==='en'));
 function close(){active=false;for(const requestId of requests)invoke('cancel_api',{requestId}).catch(()=>{});dialog.close();dialog.remove();}
 const btn=(de,en,fn)=>el('button',{type:'button',onclick:fn},t(de,en)),input=(type,value)=>el('input',{type,value:value??'',autocomplete:'off'}),field=(de,en,control)=>{control.setAttribute('aria-label',t(de,en));return el('label',{class:'settings-field'},el('span',{},t(de,en)),control);},check=(de,en,checked)=>{const control=el('input',{type:'checkbox',checked:!!checked});return {control,node:el('label',{class:'settings-check'},control,t(de,en))};};
 function page(de,en){const p=el('section',{class:'settings-page',hidden:pages.children.length>0}),b=btn(de,en,()=>{Array.from(pages.children).forEach(x=>x.hidden=x!==p);Array.from(tabs.children).forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-selected',x===b);});});if(!pages.children.length)b.classList.add('selected');b.setAttribute('role','tab');b.setAttribute('aria-selected',!pages.children.length);tabs.append(b);pages.append(p);return p;}
 const appearance=page('Oberfläche','Appearance'),ai=page('KI','AI');
 function subsection(de,en){const section=el('section',{class:'settings-subsection','aria-label':t(de,en)},el('h3',{},t(de,en)));ai.append(section);return section;}
 const assistance=subsection('KI-Hilfe','AI assistance'),api=subsection('OpenAI API','OpenAI API'),quality=subsection('Antwortqualität','Response quality'),costs=subsection('Organisationskosten (optional)','Organization costs (optional)');
 const language=el('select',{},el('option',{value:'de'},'Deutsch (DE)'),el('option',{value:'en'},'English (EN)'));language.value=settings.language||'de';const dark=check('Dunkelmodus (aus = Hellmodus)','Dark mode (off = light mode)',settings.darkMode),wrap=check('Zeilenumbruch im Editor','Wrap lines in editor',settings.wordWrap),hover=check('KI-Erklärung beim Überfahren anbieten (Anfrage erst per Klick)','Offer AI explanation on hover (request only on click)',settings.aiHover);dark.control.onchange=()=>dialog.dataset.dark=String(dark.control.checked);
 appearance.append(field('Sprache','Language',language),dark.node,wrap.node,el('p',{},t('Zeilennummern sind immer sichtbar. Lange Zeilen werden bei aktiviertem Umbruch nur optisch umgebrochen.','Line numbers are always visible. Wrapping changes only the display of long lines.')));
 const enabled=check('KI aktivieren','Enable AI',settings.aiEnabled);assistance.append(enabled.node,hover.node,el('p',{},t('Über einem Symbol verweilen und „Mit KI erklären“ anklicken. Die Antwort erscheint rechts im Chat.','Hover over a symbol and click Explain with AI. The answer appears in the chat on the right.')));
 const key=input('password',''),model=input('text',settings.model||'gpt-6-astra'),output=input('number',settings.maxOutputTokens||32768),rounds=input('number',settings.maxRequests||8);key.placeholder=settings.hasApiKey?t('Gespeicherter Schlüssel (zum Ersetzen eingeben)','Saved key (enter to replace)'):'';key.oninput=()=>apiChanged=true;output.min=1024;output.max=128000;output.step=1024;rounds.min=1;rounds.max=8;rounds.step=1;
 function keyActions(control,onRemove,offset=true){const show=el('input',{type:'checkbox',onchange:e=>control.type=e.target.checked?'text':'password'});const actions=el('div',{class:'settings-key-actions'},el('label',{},show,t('Schlüssel anzeigen','Show API key')),btn('Schlüssel entfernen','Remove key',()=>{control.value='';control.placeholder='';onRemove();}));if(!offset)actions.style.marginLeft='0';return actions;}
 async function request(route,method='GET',body=null,admin=false){const requestId=crypto.randomUUID();requests.add(requestId);try{return await invoke('api_request',{route,method,body,admin,requestId,apiKey:admin?(adminChanged?adminKey.value:null):(apiChanged?key.value:null)});}finally{requests.delete(requestId);}}
 async function run(button,target,fn){button.disabled=true;target.textContent=t('Prüfung läuft …','Checking …');try{const text=await fn();if(active)target.textContent=text;}catch(e){if(active)target.textContent=localizeError(e,settings.language);}finally{button.disabled=!enabled.control.checked;usageLabel.textContent=usageSummary(settings.language==='en');}}
 const checkKey=btn('Schlüssel und Modell prüfen','Check key and model',()=>run(checkKey,feedback,async()=>{await request('models/'+encodeURIComponent(model.value.trim()));return t('Schlüssel und Modellzugriff bestätigt. Für einen echten Antworttest „KI-Test“ wählen.','Key and model access confirmed. Choose AI test to verify an actual response.');}));
 const infer=btn('KI-Test (API-Kosten)','AI test (API charges)',()=>run(infer,feedback,async()=>{const response=await request('responses','POST',{model:model.value.trim(),input:[{role:'user',content:'Reply with OK.'}],instructions:'Respond briefly.',store:false,reasoning:{effort:'low'},max_output_tokens:4096,tools:[]});addUsage(response);if(response.status!=='completed'||!(response.output||[]).some(x=>x.type==='message'&&x.content?.some(y=>y.text)))throw Error(t('Antwort unvollständig. Modell oder Ausgabelimit prüfen.','Incomplete response. Check model or output limit.'));return t('Echte Modellantwort empfangen. Verbindung funktioniert.','Actual model response received. Connection works.');}));
 api.append(field('OpenAI-API-Schlüssel','OpenAI API key',key),keyActions(key,()=>apiChanged=true),field('Modell-ID','Model ID',model),el('div',{class:'settings-row'},el('label',{class:'settings-number'},t('Ausgabetokens / Anfrage','Output tokens / request'),output),el('label',{class:'settings-number'},t('Anfragen / Auftrag','Requests / turn'),rounds)),el('div',{class:'settings-row'},checkKey,infer),feedback,el('p',{},t('Credits: unbekannt – kein dokumentierter Guthabenabruf. Der Tokenzähler erfasst nur Antworten dieser Sitzung, nicht den Kontostand.','Credits: unknown – no documented balance endpoint. Token counts cover responses in this session, not your account balance.')),btn('OpenAI-Abrechnung öffnen','Open OpenAI billing',()=>invoke('open_external',{url:'https://platform.openai.com/settings/organization/billing/overview'}).catch(e=>feedback.textContent=localizeError(e,settings.language))),usageLabel,el('p',{class:'settings-warning'},t('Speicherung: API-Schlüssel im geschützten Anmeldespeicher des Betriebssystems. Anfragen und freigegebener Code gehen an OpenAI. Das API-Konto wird nutzungsabhängig belastet. Die Limits oben sind keine harte Geldgrenze.','Storage: API keys in the operating system credential store. Requests and permitted code are sent to OpenAI. API usage is billed to your account. The limits above are not a hard spending cap.')));
 const adminKey=input('password','');adminKey.className='settings-admin-key';adminKey.placeholder=settings.hasAdminKey?t('Gespeicherter Admin-Schlüssel (zum Ersetzen eingeben)','Saved admin key (enter to replace)'):'';adminKey.oninput=()=>{adminChanged=true;adminFeedback.textContent='';};
 const checkAdmin=btn('Organisationskosten abrufen','Fetch organization costs',()=>run(checkAdmin,adminFeedback,async()=>{return t('Kostenabruf bestätigt.\n','Cost access confirmed.\n')+await fetchBilling(request,settings.language==='en');}));
 costs.append(el('p',{},t('Optionaler OpenAI-Admin-Schlüssel für Organisationskosten','Optional OpenAI admin key for organization costs')),adminKey,keyActions(adminKey,()=>adminChanged=true,false),el('div',{class:'settings-row'},checkAdmin),adminFeedback,el('p',{},t('Nach dem Speichern erscheinen die Kosten dezent unter dem KI-Chat, sobald der Abruf gelingt. Aktualisierung alle 5 Minuten. Ohne gültigen Schlüssel bleibt die Anzeige verborgen.\n\nAngezeigt werden die Kosten der gesamten Organisation für heute und diesen Monat (UTC, USD) sowie das Monatslimit, falls verfügbar. Dies ist kein Restguthaben; Kosten können verzögert sein.\n\nDer Admin-Schlüssel wird separat im geschützten Anmeldespeicher gespeichert und nur für lesende Verwaltungsabfragen verwendet.','After saving, costs appear discreetly below the AI chat once the request succeeds. Refreshed every 5 minutes. Hidden without a valid key.\n\nShows costs for the entire organization today and this month (UTC, USD), plus the monthly limit if available. This is not a credit balance; costs may be delayed.\n\nThe admin key is stored separately in the operating system credential store and used only for read-only administration requests.')));
 const reasoning=el('select',{},...['low','medium','high','xhigh','max'].map((value,index)=>el('option',{value},t(['Niedrig','Mittel','Hoch','Sehr hoch','Maximum'][index],['Low','Medium','High','Extra high','Maximum'][index]))));reasoning.value=settings.reasoningEffort||'max';quality.append(el('p',{},t('Denkaufwand (Vorgabe: max)','Reasoning effort (default: max)')),reasoning,el('p',{},t('Maximaler Denkaufwand gibt Astra mehr Raum für anspruchsvolle Codeaufgaben. Antworten können länger dauern und mehr kosten. Gründliches Denken garantiert keinen fehlerfreien Code: Änderungen weiterhin kompilieren und testen.\n\nDas Tokenlimit unter OpenAI API gilt gemeinsam für Denken und Antwort. Neue Vorgabe: 32.768 Tokens und bis zu 8 Anfragen pro Auftrag.\n\nAndere Modelle müssen die gewählte Denkstufe unterstützen. Es erfolgt keine automatische Herabstufung. Der kurze Verbindungstest nutzt weiterhin low.','Maximum reasoning effort gives Astra more room for demanding coding tasks. Responses may take longer and cost more. Careful reasoning does not guarantee correct code: continue compiling and testing changes.\n\nThe token limit under OpenAI API covers both reasoning and the answer. New default: 32,768 tokens and up to 8 requests per turn.\n\nOther models must support the chosen effort. No automatic downgrade is performed. The short connection test still uses low.')));
 const refreshEnabled=()=>{for(const button of [checkKey,infer,checkAdmin])button.disabled=!enabled.control.checked;};enabled.control.onchange=refreshEnabled;refreshEnabled();
 const save=btn('Speichern','Save',async()=>{try{if(!/^[a-zA-Z0-9._:-]{1,100}$/.test(model.value.trim()))throw Error(t('Ungültige Modell-ID','Invalid model ID'));if(!output.checkValidity()||!rounds.checkValidity())throw Error(t('Ungültige Anfragelimits','Invalid request limits'));save.disabled=true;const next={...settings,language:language.value,model:model.value.trim(),reasoningEffort:reasoning.value,maxOutputTokens:Number(output.value),maxRequests:Number(rounds.value),darkMode:dark.control.checked,wordWrap:wrap.control.checked,aiEnabled:enabled.control.checked,aiHover:hover.control.checked};if(apiChanged){await invoke('set_secret',{kind:'api',value:key.value.trim()});next.hasApiKey=!!key.value.trim();}if(adminChanged){await invoke('set_secret',{kind:'admin',value:adminKey.value.trim()});next.hasAdminKey=!!adminKey.value.trim();}await context.setSettings(next);close();}catch(e){context.notify?.(localizeError(e,settings.language));feedback.textContent=localizeError(e,settings.language);Array.from(pages.children).forEach(x=>x.hidden=x!==ai);Array.from(tabs.children).forEach((x,i)=>{x.classList.toggle('selected',i===1);x.setAttribute('aria-selected',i===1);});}finally{save.disabled=false;}});
 shell.append(el('div',{class:'settings-title'},t('Einstellungen','Settings'),el('button',{type:'button','aria-label':t('Schließen','Close'),title:t('Schließen','Close'),onclick:close},'×')),tabs,pages,el('div',{class:'settings-footer'},save,btn('Abbrechen','Cancel',close)));dialog.append(shell);document.body.append(dialog);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.showModal();return dialog;
}
export function formatBilling(result,en=false){const now=new Date(),day=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())/1000;let month=0,today=0;for(const bucket of result.data||[])for(const row of bucket.results||[]){if(row.amount?.currency&&row.amount.currency.toLowerCase()!=='usd')continue;const value=Number(row.amount?.value||0);month+=value;if(bucket.start_time>=day)today+=value;}return `${en?'Today':'Heute'}: $${today.toFixed(2)} · ${en?'Month':'Monat'}: $${month.toFixed(2)} (UTC, USD)${result.has_more?' · '+(en?'partial data':'unvollständige Daten'):''}`;}

export async function fetchBilling(request,en=false){const now=new Date(),start=Math.floor(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)/1000),base='organization/costs?start_time='+start+'&bucket_width=1d&limit=31';const data=[];let page='',seen=new Set();for(let round=0;round<20;round++){const result=await request(base+(page?'&page='+encodeURIComponent(page):''),'GET',null,true);if(!Array.isArray(result.data))throw Error(localizeError('Invalid organization costs response.',en?'en':'de'));for(const bucket of result.data){if(!Number.isFinite(bucket.start_time)||!Array.isArray(bucket.results))throw Error(localizeError('Invalid organization costs bucket.',en?'en':'de'));for(const row of bucket.results)if(String(row.amount?.currency).toLowerCase()!=='usd'||!Number.isFinite(Number(row.amount?.value))||row.amount?.value==null)throw Error(localizeError('Invalid organization costs amount.',en?'en':'de'));}data.push(...result.data);if(!result.has_more){let summary=formatBilling({data},en);try{const limit=await request('organization/spend_limit','GET',null,true);if(limit.object==='organization.spend_limit'&&limit.interval==='month'&&String(limit.currency).toLowerCase()==='usd'&&['enforcing','inactive'].includes(limit.enforcement?.status)&&Number.isFinite(Number(limit.threshold_amount))&&Number(limit.threshold_amount)>=0)summary+=' · '+(en?'Monthly limit':'Monatslimit')+': $'+(Number(limit.threshold_amount)/100).toFixed(2)+(limit.enforcement.status==='inactive'?(en?' (inactive)':' (inaktiv)'):'');}catch{}return summary;}if(!result.next_page||seen.has(result.next_page))throw Error(localizeError('Invalid organization costs pagination.',en?'en':'de'));page=result.next_page;seen.add(page);}throw Error(localizeError('Organization costs pagination limit reached.',en?'en':'de'));}
