// Source structure only: this module never executes contract expressions.
const scopeKinds = new Set(['entry','function','fn','delegate']);
const byOrder = (a,b)=>(a.order??a.start??0)-(b.order??b.start??0)||a.id.localeCompare(b.id);
export function actionFor(nodes,id){const map=new Map(nodes.map(n=>[n.id,n]));let n=map.get(id),seen=new Set();while(n&&!seen.has(n.id)){if(scopeKinds.has(n.kind))return n.id;seen.add(n.id);n=map.get(n.parent);}const ancestor=id;return nodes.filter(n=>scopeKinds.has(n.kind)).sort(byOrder).find(n=>{let p=n;const seen=new Set();while(p&&!seen.has(p.id)){if(p.id===ancestor)return true;seen.add(p.id);p=map.get(p.parent);}return false;})?.id||nodes.filter(n=>scopeKinds.has(n.kind)).sort(byOrder)[0]?.id||null;}
export function valueColor(edge){if(edge.kind==='control'||edge.kind==='contains')return '#8994a6';const key=(edge.sourceId||edge.from)+'|'+(edge.valueName||'');let hash=2166136261;for(const c of key)hash=Math.imul(hash^c.charCodeAt(0),16777619);return `hsl(${(hash>>>0)%360} 65% 57%)`;}
export function describeEdge(edge,nodes,language='de'){const en=language==='en',map=new Map(nodes.map(n=>[n.id,n]));const a=map.get(edge.sourceId||edge.from),b=map.get(edge.targetId||edge.to);const purpose=en?(edge.labelEn||edge.label||'uses'):(edge.label||'verwendet');const title=n=>en&&n?.kind==='check'&&/^Prüfung \d+$/.test(n.name)?n.name.replace('Prüfung ','Check '):en&&n?.kind==='transition'&&n.name==='Nachfolger festlegen'?'Define successors':n?.name;const route=`${en?'From':'Von'}: ${title(a)||edge.sourceId||edge.from}\n${en?'To':'Nach'}: ${title(b)||edge.targetId||edge.to}`;if(edge.kind==='contains')return `${en?'Structural membership':'Strukturelle Zugehörigkeit'}\n${route}\n${en?'Declared containment; not execution order.':'Deklarierte Zugehörigkeit; keine Ausführungsreihenfolge.'}`;if(edge.kind==='control')return `${en?'Execution order':'Ausführungsreihenfolge'}\n${route}\n${purpose}\n${en?'Carries no value; no data type.':'Transportiert keinen Wert; kein Datentyp.'}`;return `${en?'Value':'Wert'}: ${edge.valueName||(en?'Not specified':'Nicht angegeben')}\n${en?'Data type':'Datentyp'}: ${edge.valueType||(en?'Not statically determined':'Nicht statisch bestimmt')}\n${route}\n${en?'Purpose':'Verwendung'}: ${purpose}`;}
function layoutHierarchy(nodes,edges,{collapsed,focusId,includeScope}){
 const map=new Map(nodes.map(n=>[n.id,n])),children=new Map();for(const n of nodes){if(!children.has(n.parent))children.set(n.parent,[]);children.get(n.parent).push(n);}for(const list of children.values())list.sort(byOrder);
 const cards=new Map(),groups=[],combined=[],visiting=new Set();
 const pathFor=route=>route.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');
 function append(part,x,y){for(const[id,r]of part.cards)cards.set(id,{...r,x:r.x+x,y:r.y+y});for(const e of part.edges){const route=e.route.map(p=>({x:p.x+x,y:p.y+y}));combined.push({...e,route,path:pathFor(route)});}}
 function place(n,x,y,depth){if(visiting.has(n.id))return{width:0,height:0};visiting.add(n.id);const nested=children.get(n.id)||[],isGroup=nested.length>0;cards.set(n.id,{x:x+24,y:y+24,w:224,h:76});
  if(!isGroup||collapsed.has(n.id)){if(isGroup)groups.push({id:n.id,x,y,w:272,h:124,depth,expanded:false});visiting.delete(n.id);return{width:272,height:124};}
  let width=272,height=124;
  if(scopeKinds.has(n.kind)){const part=layoutNetwork(nodes,edges,{collapsed,focusId:n.id});append(part,x+24,y+112);width=Math.max(width,part.width+48);height=part.height+136;}
  else{let nextY=y+124;for(const child of nested){const size=place(child,x+24,nextY,depth+1);width=Math.max(width,size.width+48);nextY+=size.height+28;}height=Math.max(124,nextY-y);}
  groups.push({id:n.id,x,y,w:width,h:height,depth,expanded:true});visiting.delete(n.id);return{width,height};
 }
 const roots=focusId==='*'?nodes.filter(n=>!map.has(n.parent)).sort(byOrder):[map.get(focusId)].filter(Boolean);let y=24,width=400;for(const root of roots){const size=place(root,24,y,0);y+=size.height+40;width=Math.max(width,size.width+48);}
 const provenance=e=>[e.sourceId||e.from,e.targetId||e.to,e.kind,e.valueName||'',e.kind==='control'?(e.labelEn||e.label||''):''].join('|');const already=new Set(combined.map(provenance));
 function visibleRepresentative(id){let n=map.get(id),visible=null,seen=new Set();while(n&&!seen.has(n.id)){seen.add(n.id);if(cards.has(n.id)){visible=n.id;break;}n=map.get(n.parent);}return visible;}
 const pending=[];for(const e of edges){if(already.has(provenance(e)))continue;const from=visibleRepresentative(e.from),to=visibleRepresentative(e.to);if(!from||!to||from===to)continue;
  // Membership lines connect only their declared visible scope, never hidden
  // descendants to an unrelated enclosing scope or an invented execution step.
  if(e.kind==='contains'&&(from!==e.from||to!==e.to||!['app','actor','state','file'].includes(map.get(e.from)?.kind)))continue;
  const key=[from,to,e.kind,e.valueName||'',e.from,e.to,e.kind==='control'?(e.labelEn||e.label||''):''].join('|');pending.push({...e,from,to,sourceId:e.sourceId||e.from,targetId:e.targetId||e.to,key});already.add(provenance(e));}
 const originKey=e=>(e.sourceId||e.from)+'|'+(map.get(e.sourceId||e.from)?.role==='input'?'':(e.valueName||''));const origins=[...new Set(edges.filter(e=>e.kind==='value').map(originKey))].sort();const palette=new Map(origins.map((key,i)=>[key,`hsl(${(i*137.50776405+205)%360} 65% 57%)`]));
 const occupied=combined.flatMap(e=>e.route.slice(1).map((p,i)=>[e.route[i],p]));for(const e of pending){const a=cards.get(e.from),b=cards.get(e.to);const out=pending.filter(x=>x.from===e.from),into=pending.filter(x=>x.to===e.to);const start={x:a.x+a.w,y:a.y+a.h*(out.indexOf(e)+1)/(out.length+1)},end={x:b.x,y:b.y+b.h*(into.indexOf(e)+1)/(into.length+1)};e.route=routeOrthogonal(start,end,cards,occupied);e.path=pathFor(e.route);e.color=e.kind==='value'?palette.get(originKey(e)):valueColor(e);combined.push(e);for(let i=1;i<e.route.length;i++)occupied.push([e.route[i-1],e.route[i]]);}
 return{cards,edges:combined,groups:groups.sort((a,b)=>a.depth-b.depth),width:Math.max(width,...combined.flatMap(e=>e.route.map(p=>p.x+35))),height:Math.max(250,y,...combined.flatMap(e=>e.route.map(p=>p.y+35))),focusId};
}

export function layoutNetwork(nodes,edges,{collapsed=new Set(),focusId,includeScope=false}={}){
 const requested=nodes.find(n=>n.id===focusId);if(focusId==='*'||(requested&&(['app','actor','state','file'].includes(requested.kind)||includeScope)))return layoutHierarchy(nodes,edges,{collapsed,focusId,includeScope});
 const colorNodes=new Map(nodes.map(n=>[n.id,n]));const originKey=e=>(e.sourceId||e.from)+'|'+(colorNodes.get(e.sourceId||e.from)?.role==='input'?'':(e.valueName||''));const origins=[...new Set(edges.filter(e=>e.kind==='value').map(originKey))].sort();const palette=new Map(origins.map((key,i)=>[key,`hsl(${(i*137.50776405+205)%360} 65% 57%)`]));
 const map=new Map(nodes.map(n=>[n.id,n])),children=new Map();for(const n of nodes){if(!children.has(n.parent))children.set(n.parent,[]);children.get(n.parent).push(n);}for(const list of children.values())list.sort(byOrder);
 const focus=actionFor(nodes,focusId);const inside=id=>{let n=map.get(id),seen=new Set();while(n&&!seen.has(n.id)){if(n.id===focus)return true;seen.add(n.id);n=map.get(n.parent);}return !focus;};
 const eligible=nodes.filter(n=>n.id!==focus&&inside(n.id)&&!(n.role==='scope'&&!scopeKinds.has(n.kind)));
 // Rule groups are not scope nodes; enclosing app/actor declarations are headers.
 const visible=new Map();function representative(id){let n=map.get(id),result=n,seen=new Set();while(n&&n.id!==focus&&!seen.has(n.id)){seen.add(n.id);if(collapsed.has(n.id))result=n;n=map.get(n.parent);}return result&&inside(result.id)?result.id:null;}
 for(const n of eligible)if(representative(n.id)===n.id)visible.set(n.id,n);
 const descendants=id=>{const result=[];function visit(p){for(const n of children.get(p)||[]){if(visible.has(n.id))result.push(n);visit(n.id);}}visit(id);return result;};
 const projected=[],dedup=new Set();for(const e of edges){if(e.kind==='contains')continue;let from=representative(e.from),to=representative(e.to);if(!visible.has(from)||!visible.has(to)||from===to)continue;
  // An entering sequence reaches the first source statement, not the group join.
  if(e.kind==='control'&&!collapsed.has(to)&&!descendants(to).some(n=>n.id===from)){const nested=descendants(to).filter(n=>n.role!=='output').sort(byOrder);if(nested.length)to=nested[0].id;}
  const key=[from,to,e.kind,e.valueName||'',e.from,e.to,e.kind==='control'?(e.labelEn||e.label||''):''].join('|');if(dedup.has(key))continue;dedup.add(key);projected.push({...e,from,to,sourceId:e.sourceId||e.from,targetId:e.targetId||e.to,key});}
 const constraints=projected.map(e=>[e.from,e.to]);
 // Expanding a source statement cannot move a constant member before the
 // preceding source statement just because that member has no value inputs.
 for(const e of edges.filter(e=>e.kind==='control')){const from=representative(e.from),to=representative(e.to);if(!visible.has(from)||!visible.has(to)||from===to||collapsed.has(to))continue;const nested=descendants(to);if(nested.some(n=>n.id===from))continue;for(const child of nested)constraints.push([from,child.id]);}for(const n of visible.values())if(!collapsed.has(n.id)){for(const child of descendants(n.id))constraints.push([child.id,n.id]);}
 const ranks=new Map([...visible.keys()].map(id=>[id,0])),incoming=new Map(),outgoing=new Map();for(const id of visible.keys()){incoming.set(id,[]);outgoing.set(id,[]);}for(const[a,b]of constraints){if(a!==b&&incoming.has(b)&&outgoing.has(a)){incoming.get(b).push(a);outgoing.get(a).push(b);}}
 // Topological layers; cyclic source constructs keep a bounded source-order fallback.
 const indegree=new Map([...incoming].map(([id,list])=>[id,new Set(list).size])),queue=[...visible.values()].filter(n=>!indegree.get(n.id)).sort(byOrder),done=new Set();while(queue.length){const n=queue.shift();done.add(n.id);for(const next of new Set(outgoing.get(n.id))){ranks.set(next,Math.max(ranks.get(next),ranks.get(n.id)+1));indegree.set(next,indegree.get(next)-1);if(!indegree.get(next)){queue.push(visible.get(next));queue.sort(byOrder);}}}
 for(const n of [...visible.values()].filter(n=>!done.has(n.id)).sort(byOrder))ranks.set(n.id,Math.max(1,...incoming.get(n.id).filter(id=>done.has(id)).map(id=>ranks.get(id)+1)));
 for(const n of visible.values())if(n.role==='input')ranks.set(n.id,0);else ranks.set(n.id,ranks.get(n.id)+1);
 const maxRank=Math.max(1,...ranks.values())+1;for(const n of visible.values())if(n.role==='output')ranks.set(n.id,maxRank);
 const layers=new Map();for(const n of visible.values()){const rank=ranks.get(n.id);if(!layers.has(rank))layers.set(rank,[]);layers.get(rank).push(n);}for(const layer of layers.values())layer.sort(byOrder);
 // Alternating barycentric sweeps spread related branches vertically.
 const rankOrder=[...layers.keys()].sort((a,b)=>a-b);let rows=new Map();for(const layer of layers.values())layer.forEach((n,i)=>rows.set(n.id,i));for(let pass=0;pass<6;pass++){const direction=pass%2?outgoing:incoming;for(const rank of pass%2?[...rankOrder].reverse():rankOrder){const layer=layers.get(rank),score=n=>{const adjacent=direction.get(n.id)||[];return adjacent.length?adjacent.reduce((sum,id)=>sum+(rows.get(id)||0),0)/adjacent.length:rows.get(n.id);};layer.sort((a,b)=>score(a)-score(b)||byOrder(a,b));layer.forEach((n,i)=>rows.set(n.id,i));}}
 const cards=new Map();
 const valueIncoming=new Map();for(const e of projected.filter(e=>e.kind==='value')){if(!valueIncoming.has(e.to))valueIncoming.set(e.to,[]);valueIncoming.get(e.to).push(e.from);}
 for(const rank of rankOrder){const layer=layers.get(rank),desired=new Map();for(const n of layer){const values=(valueIncoming.get(n.id)||[]).filter(id=>cards.has(id));const preceding=values.length?values:(incoming.get(n.id)||[]).filter(id=>cards.has(id));const y=preceding.length?preceding.reduce((sum,id)=>sum+cards.get(id).y,0)/preceding.length:65+(rows.get(n.id)||0)*132;desired.set(n.id,y);}
 layer.sort((a,b)=>desired.get(a.id)-desired.get(b.id)||byOrder(a,b));let previous=-Infinity;for(const n of layer){const y=Math.max(32,desired.get(n.id),previous+112);cards.set(n.id,{x:40+rank*290,y,w:224,h:76});previous=y;}}
 const ordered=[...projected].sort((a,b)=>((cards.get(a.from).y+cards.get(a.to).y)-(cards.get(b.from).y+cards.get(b.to).y))||a.key.localeCompare(b.key));const ports=new Map();for(const id of visible.keys()){const outs=ordered.filter(e=>e.from===id).sort((a,b)=>cards.get(a.to).y-cards.get(b.to).y||a.key.localeCompare(b.key)),ins=ordered.filter(e=>e.to===id).sort((a,b)=>cards.get(a.from).y-cards.get(b.from).y||a.key.localeCompare(b.key));outs.forEach((e,i)=>ports.set(e.key+'out',(i+1)/(outs.length+1)));ins.forEach((e,i)=>ports.set(e.key+'in',(i+1)/(ins.length+1)));}
 const occupied=[];for(const e of ordered){const a=cards.get(e.from),b=cards.get(e.to);const start={x:a.x+a.w,y:a.y+a.h*ports.get(e.key+'out')},end={x:b.x,y:b.y+b.h*ports.get(e.key+'in')};e.route=routeOrthogonal(start,end,cards,occupied);e.path=e.route.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');e.color=e.kind==='value'?palette.get(originKey(e)):valueColor(e);for(let i=1;i<e.route.length;i++)occupied.push([e.route[i-1],e.route[i]]);}
 return{cards,edges:ordered,focusId:focus,width:Math.max(400,...[...cards.values()].map(r=>r.x+r.w+50),...ordered.flatMap(e=>e.route.map(p=>p.x+35))),height:Math.max(250,...[...cards.values()].map(r=>r.y+r.h+65),...ordered.flatMap(e=>e.route.map(p=>p.y+35)))};
}
function crosses(a,b,r){if(a.x===b.x)return a.x>r.x&&a.x<r.x+r.w&&Math.max(a.y,b.y)>r.y&&Math.min(a.y,b.y)<r.y+r.h;return a.y>r.y&&a.y<r.y+r.h&&Math.max(a.x,b.x)>r.x&&Math.min(a.x,b.x)<r.x+r.w;}
export function routeOrthogonal(start,end,cards,occupied=[]){
 const rects=[...cards.values()].map(r=>({x:r.x-8,y:r.y-8,w:r.w+16,h:r.h+16}));const a={x:start.x+18,y:start.y},b={x:end.x-18,y:end.y};const xs=[...new Set([a.x,b.x,12,...rects.flatMap(r=>[r.x-12,r.x+r.w+12])])].sort((x,y)=>x-y),ys=[...new Set([a.y,b.y,20,...rects.flatMap(r=>[r.y-14,r.y+r.h+14])])].sort((x,y)=>x-y);
 const ix=xs.indexOf(a.x),iy=ys.indexOf(a.y),target=xs.indexOf(b.x)+','+ys.indexOf(b.y);const heap=[],distance=new Map(),parent=new Map();const push=item=>{heap.push(item);let i=heap.length-1;while(i){let p=(i-1)>>1;if(heap[p].f<=item.f)break;heap[i]=heap[p];i=p;}heap[i]=item;};const pop=()=>{const top=heap[0],last=heap.pop();if(heap.length){let i=0;while(i*2+1<heap.length){let child=i*2+1;if(child+1<heap.length&&heap[child+1].f<heap[child].f)child++;if(heap[child].f>=last.f)break;heap[i]=heap[child];i=child;}heap[i]=last;}return top;};
 const first={x:ix,y:iy,d:0,g:0,key:`${ix},${iy},0`};first.f=Math.abs(a.x-b.x)+Math.abs(a.y-b.y);push(first);distance.set(first.key,0);let finish;
 while(heap.length){const current=pop();if(current.g!==distance.get(current.key))continue;if(`${current.x},${current.y}`===target){finish=current;break;}for(const[dx,dy,d]of [[1,0,1],[-1,0,1],[0,1,2],[0,-1,2]]){const x=current.x+dx,y=current.y+dy;if(x<0||y<0||x>=xs.length||y>=ys.length)continue;const p={x:xs[current.x],y:ys[current.y]},q={x:xs[x],y:ys[y]};if(rects.some(r=>crosses(p,q,r)))continue;let penalty=0;for(const[u,v]of occupied){if(p.x===q.x&&u.x===v.x&&p.x===u.x&&Math.min(Math.max(p.y,q.y),Math.max(u.y,v.y))>Math.max(Math.min(p.y,q.y),Math.min(u.y,v.y)))penalty+=12;else if(p.y===q.y&&u.y===v.y&&p.y===u.y&&Math.min(Math.max(p.x,q.x),Math.max(u.x,v.x))>Math.max(Math.min(p.x,q.x),Math.min(u.x,v.x)))penalty+=12;}
 const g=current.g+Math.abs(p.x-q.x)+Math.abs(p.y-q.y)+(current.d&&current.d!==d?18:0)+penalty,key=`${x},${y},${d}`;if(g>=(distance.get(key)??Infinity))continue;distance.set(key,g);parent.set(key,current);push({x,y,d,g,key,f:g+Math.abs(q.x-b.x)+Math.abs(q.y-b.y)});}}
 const middle=[];for(let step=finish;step;step=parent.get(step.key))middle.push({x:xs[step.x],y:ys[step.y]});middle.reverse();const points=middle.length?[start,...middle,end]:[start,a,{x:a.x,y:20},{x:b.x,y:20},b,end];return points.filter((p,i)=>!i||p.x!==points[i-1].x||p.y!==points[i-1].y).filter((p,i,all)=>!i||i===all.length-1||!((all[i-1].x===p.x&&p.x===all[i+1].x)||(all[i-1].y===p.y&&p.y===all[i+1].y)));
}
