import {test,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
test.use({browserName:process.env.ARGENT_BROWSER==='webkit'?'webkit':'chromium',channel:process.env.ARGENT_BROWSER==='webkit'?undefined:'msedge'});
let server,url;
test.beforeAll(async()=>{server=createServer(async(req,res)=>{try{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end('<html><head><link rel="stylesheet" href="/assistant.css"></head><body><div id="assistant" style="width:390px;height:700px"></div></body></html>');}else{res.setHeader('Content-Type',req.url.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(new URL('../frontend/'+req.url.slice(1),import.meta.url)));}}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;});
test.afterAll(()=>server.close());
test('proposal is preview only, stale source is rejected, consent strips tools',async({page})=>{await page.goto(url);await page.evaluate(async()=>{const {mountAssistant}=await import('/assistant.js');let settings={language:'de',model:'fixture',maxRequests:2,aiEnabled:true};window.docs=[{path:'C:/project/main.ag',text:'original',generated:false}];window.requests=[];window.changed=[];window.ai=mountAssistant(document.querySelector('#assistant'),{getSettings:()=>settings,getProjectRoot:()=> 'C:/project',getDocuments:()=>window.docs,getDocument:()=>window.docs[0],listFiles:()=>['main.ag'],invoke:async(n,a)=>{if(n==='read_ai_file')return 'original';if(n==='api_request'){window.requests.push(a);if(window.requests.length===1)return {status:'completed',output:[{type:'function_call',name:'propose_file',arguments:JSON.stringify({path:'main.ag',content:'proposed'}),call_id:'proposal'}]};return{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Review the proposal.'}]}]};}throw Error(n);},updateDocument:async(path,text)=>{window.changed.push({path,text});window.docs[0].text=text;}});});await page.locator('.ai-share input').check();await page.locator('.ai-prompt').fill('Ändere diese Datei');await page.locator('.ai-prompt').press('Enter');await expect(page.getByRole('button',{name:'Vorschlag übernehmen',exact:true})).toBeEnabled();expect(await page.evaluate(()=>window.changed.length)).toBe(0);await page.evaluate(()=>window.docs[0].text='edited meanwhile');await page.getByRole('button',{name:'Vorschlag übernehmen',exact:true}).click();expect(await page.evaluate(()=>window.changed.length)).toBe(0);await page.getByRole('button',{name:'KI-Assistent',exact:true}).click();await expect(page.locator('.ai-transcript')).toContainText('Datei wurde inzwischen geändert');await page.getByRole('button',{name:'Änderungsvorschlag',exact:true}).click();await page.getByRole('button',{name:'Vorschlag verwerfen',exact:true}).click();await page.getByRole('button',{name:'KI-Assistent',exact:true}).click();await page.locator('.ai-share input').uncheck();await page.locator('.ai-prompt').fill('Hallo');await page.locator('.ai-prompt').press('Enter');await expect.poll(()=>page.evaluate(()=>window.requests.length)).toBe(3);const last=await page.evaluate(()=>window.requests.at(-1).body);expect(last.tools.map(t=>t.name)).toEqual(['list_examples','load_example','read_reference']);expect(JSON.stringify(last.input)).not.toContain('original');expect(JSON.stringify(last.input)).not.toContain('proposed');});
test('settings Cancel does not save modified secrets; AI controls share one tab without toolchain requests',async({page})=>{await page.goto(url);await page.evaluate(async()=>{const {showSettings}=await import('/settings.js');window.calls=[];await showSettings({getSettings:()=>({language:'de',model:'fixture',maxRequests:8,maxOutputTokens:32768,hasApiKey:true}),invoke:async(n,a)=>{window.calls.push({n,a});return{};},setSettings:async()=>window.calls.push({n:'save'})});});for(const name of ['Oberfläche','KI'])await expect(page.getByRole('tab',{name,exact:true})).toBeVisible();await expect(page.getByRole('tab')).toHaveCount(2);await expect(page.getByLabel('KI aktivieren',{exact:true})).toBeHidden();await page.screenshot({path:'qa/settings-appearance.png'});await page.getByRole('tab',{name:'KI',exact:true}).click();await expect(page.getByLabel('KI aktivieren',{exact:true})).not.toBeChecked();await expect(page.getByRole('button',{name:'Schlüssel und Modell prüfen',exact:true})).toBeDisabled();await page.getByLabel('KI aktivieren',{exact:true}).check();await expect(page.getByRole('button',{name:'Schlüssel und Modell prüfen',exact:true})).toBeEnabled();await expect(page.getByText('Denkaufwand (Vorgabe: max)',{exact:true})).toBeVisible();await expect(page.locator('.settings-admin-key')).toBeVisible();expect(await page.evaluate(()=>window.calls.some(c=>c.n.startsWith('toolchain_')))).toBe(false);await page.screenshot({path:'qa/settings-api.png'});await page.getByLabel('OpenAI-API-Schlüssel',{exact:true}).fill('fixture-key');await page.getByRole('button',{name:'Abbrechen',exact:true}).click();expect(await page.evaluate(()=>window.calls.some(c=>c.n==='set_secret'||c.n==='save'))).toBe(false);});
test('disabling AI clears project context and proposals before re-enabling',async({page})=>{
 await page.goto(url);await page.evaluate(async()=>{const {mountAssistant}=await import('/assistant.js');window.settings={language:'en',model:'fixture',aiEnabled:true,maxRequests:2};window.requests=[];window.ai=mountAssistant(document.querySelector('#assistant'),{getSettings:()=>window.settings,getProjectRoot:()=> 'C:/project',getDocuments:()=>[{path:'C:/project/main.ag',text:'PRIVATE SOURCE'}],getDocument:()=>({path:'C:/project/main.ag'}),listFiles:()=>['main.ag'],invoke:async(n,a)=>{if(n==='read_ai_file')return 'PRIVATE SOURCE';if(n==='cancel_api')return;if(n==='api_request'){window.requests.push(structuredClone(a));return window.requests.length===1?{status:'completed',output:[{type:'function_call',name:'propose_file',arguments:JSON.stringify({path:'main.ag',content:'PRIVATE PROPOSAL'}),call_id:'p'}]}:{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'review'}]}]};}throw Error(n);}});});
 await page.locator('.ai-share input').check();await page.locator('.ai-prompt').fill('edit');await page.locator('.ai-prompt').press('Enter');await expect(page.getByRole('button',{name:'Apply proposal',exact:true})).toBeEnabled();
 await page.evaluate(()=>{window.settings.aiEnabled=false;window.ai.refresh();});await expect(page.getByRole('button',{name:'Apply proposal',exact:true})).toBeDisabled();await expect(page.getByLabel('Proposal',{exact:true})).toHaveValue('');
 await page.evaluate(()=>{window.settings.aiEnabled=true;window.ai.refresh();});await page.getByRole('button',{name:'AI assistant',exact:true}).click();await expect(page.locator('.ai-share input')).not.toBeChecked();await page.locator('.ai-prompt').fill('hello');await page.locator('.ai-prompt').press('Enter');await expect.poll(()=>page.evaluate(()=>window.requests.length)).toBe(3);expect(await page.evaluate(()=>JSON.stringify(window.requests.at(-1).body))).not.toContain('PRIVATE');
});

test('revocation during a pending source read cannot restore context or send a request',async({page})=>{
 await page.goto(url);await page.evaluate(async()=>{const {mountAssistant}=await import('/assistant.js');window.settings={language:'en',model:'fixture',aiEnabled:true};window.requests=[];window.ai=mountAssistant(document.querySelector('#assistant'),{getSettings:()=>window.settings,getProjectRoot:()=> 'C:/project',getDocument:()=>({path:'C:/project/main.ag'}),listFiles:()=>['main.ag'],invoke:async(n,a)=>{if(n==='read_ai_file')return await new Promise(r=>window.finishRead=r);if(n==='cancel_api')return;if(n==='api_request'){window.requests.push(a);return{status:'completed',output:[]};}throw Error(n);}});});
 await page.locator('.ai-share input').check();await page.locator('.ai-prompt').fill('read');await page.locator('.ai-prompt').press('Enter');await expect.poll(()=>page.evaluate(()=>!!window.finishRead)).toBe(true);await page.evaluate(()=>{window.settings.aiEnabled=false;window.ai.refresh();window.settings.aiEnabled=true;window.ai.refresh();window.finishRead('PRIVATE LATE');});await expect.poll(()=>page.evaluate(()=>window.ai.isBusy())).toBe(false);expect(await page.evaluate(()=>window.requests.length)).toBe(0);await page.locator('.ai-prompt').fill('hello');await page.locator('.ai-prompt').press('Enter');await expect.poll(()=>page.evaluate(()=>window.requests.length)).toBe(1);expect(await page.evaluate(()=>JSON.stringify(window.requests[0]))).not.toContain('PRIVATE');
});

test('already-open documents still require a successful native scoped read',async({page})=>{
 await page.goto(url);await page.evaluate(async()=>{const {mountAssistant}=await import('/assistant.js');window.requests=[];window.ai=mountAssistant(document.querySelector('#assistant'),{getSettings:()=>({language:'en',model:'fixture',aiEnabled:true}),getProjectRoot:()=> 'C:/project',getDocuments:()=>[{path:'C:/project/linked/main.ag',text:'PRIVATE OPEN BUFFER'}],getDocument:()=>({path:'C:/project/linked/main.ag'}),listFiles:()=>['linked/main.ag'],invoke:async(n,a)=>{if(n==='read_ai_file')throw Error('Linked project paths are unsupported for AI access');window.requests.push({n,a});}});});
 await page.locator('.ai-share input').check();await page.locator('.ai-prompt').fill('explain');await page.locator('.ai-prompt').press('Enter');await expect(page.locator('.ai-transcript')).toContainText('Linked project paths');expect(await page.evaluate(()=>window.requests.some(x=>x.n==='api_request'))).toBe(false);
});
test('late tool output cannot resurrect revoked project context',async({page})=>{
 await page.goto(url);await page.evaluate(async()=>{const {mountAssistant}=await import('/assistant.js');window.settings={language:'en',model:'fixture',aiEnabled:true,maxRequests:3};window.requests=[];window.ai=mountAssistant(document.querySelector('#assistant'),{getSettings:()=>window.settings,getProjectRoot:()=> 'C:/project',listFiles:()=>[],readBuildFile:()=>new Promise(r=>window.finishTool=r),invoke:async(n,a)=>{if(n==='cancel_api')return;if(n==='api_request'){window.requests.push(structuredClone(a));return window.requests.length===1?{status:'completed',output:[{type:'function_call',name:'read_build_file',arguments:JSON.stringify({path:'artifact.json',offset:'0'}),call_id:'p'}]}:{status:'completed',output:[]};}throw Error(n);}});});
 await page.locator('.ai-share input').check();await page.locator('.ai-prompt').fill('read build');await page.locator('.ai-prompt').press('Enter');await expect.poll(()=>page.evaluate(()=>!!window.finishTool)).toBe(true);await page.evaluate(()=>{window.settings.aiEnabled=false;window.ai.refresh();window.settings.aiEnabled=true;window.ai.refresh();window.finishTool('PRIVATE LATE BUILD');});await expect.poll(()=>page.evaluate(()=>window.ai.isBusy())).toBe(false);expect(await page.evaluate(()=>window.requests.length)).toBe(1);await page.locator('.ai-prompt').fill('hello');await page.locator('.ai-prompt').press('Enter');await expect.poll(()=>page.evaluate(()=>window.requests.length)).toBe(2);expect(await page.evaluate(()=>JSON.stringify(window.requests.at(-1).body))).not.toContain('PRIVATE');
});

test('AI compile results exclude unrelated open document snapshots and logs',async({page})=>{
 await page.goto(url);await page.evaluate(async()=>{const {mountAssistant}=await import('/assistant.js');window.ai=mountAssistant(document.querySelector('#assistant'),{getSettings:()=>({language:'en',model:'fixture',aiEnabled:true}),getProjectRoot:()=> 'C:/project',build:async()=>({success:true,exitCode:0,output:'C:/project/build/123',files:['artifact.json'],sources:[{text:'PRIVATE OPEN DOCUMENT'}],stdout:'PRIVATE COMPILER LOG'}),invoke:async()=>{}});});await page.locator('.ai-share input').check();const result=await page.evaluate(()=>window.ai.executeTool('compile',{}));expect(result.success).toBe(true);expect(JSON.stringify(result)).not.toContain('PRIVATE');
});
