import test from 'node:test';
import assert from 'node:assert/strict';
import {runAssistantTeam,requestLimit,READ_ONLY_TOOLS} from '../frontend/assistant-team.js';
const complete=text=>({status:'completed',output:[{type:'message',content:[{text}]}]});
test('three workers start concurrently with readonly tools and same model settings',async()=>{let starts=0;const gates=[];const pending=runAssistantTeam({request:body=>{assert.equal(body.model,'fixture');assert.equal(body.reasoning.effort,'max');assert.deepEqual(body.tools.map(x=>x.name),['read_file']);starts++;return new Promise(resolve=>gates.push(()=>resolve(complete('report'))));},executeTool:()=>assert.fail(),tools:[{name:'read_file'},{name:'compile'},{name:'propose_file'}],input:[],instructions:'skill',settings:{model:'fixture'},check:()=>{}});await Promise.resolve();assert.equal(starts,3);gates.forEach(f=>f());assert.equal((await pending).length,3);});
test('workers reject mutation calls and share bounded per-role budget across followups',async()=>{let calls=0,mutations=0;const budget=new Map();const options={request:async()=>{calls++;return {status:'completed',output:[{type:'function_call',name:'compile',arguments:'{}',call_id:'c'}]};},executeTool:()=>{mutations++;},tools:[],input:[],instructions:'skill',settings:{maxRequests:1},check:()=>{},budget};await runAssistantTeam(options);await runAssistantTeam(options);assert.equal(calls,3);assert.equal(mutations,0);});
test('revoked late responses never become reports',async()=>{let revoked=false;const gates=[];const pending=runAssistantTeam({request:()=>new Promise(resolve=>gates.push(resolve)),executeTool:()=>{},tools:[],input:[],instructions:'skill',settings:{},check:()=>{if(revoked)throw Error('revoked');}});revoked=true;gates.forEach(resolve=>resolve(complete('PRIVATE')));await assert.rejects(pending,/revoked/);});
test('worker failure is explicit while successful reviews remain available',async()=>{let n=0;const reports=await runAssistantTeam({request:async()=>{if(n++===0)throw Error('offline');return complete('ok');},executeTool:()=>{},tools:[],input:[],instructions:'skill',settings:{},check:()=>{}});assert.match(reports[0].error,/offline/);assert.equal(reports[1].report,'ok');assert.equal(reports[0].incomplete,true);});
test('request limits are clamped and mutators excluded',()=>{assert.equal(requestLimit(99),8);assert.equal(requestLimit(-1),1);for(const name of ['compile','propose_file','verify_proposal','load_example'])assert.equal(READ_ONLY_TOOLS.has(name),false);});
