import {test,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
test.use({browserName:process.env.ARGENT_BROWSER==='webkit'?'webkit':'chromium',channel:process.env.ARGENT_BROWSER==='webkit'?undefined:'msedge'});
let server,url;
test.beforeAll(async()=>{server=createServer(async(req,res)=>{try{if(req.url==='/')res.end('<div id="assistant"></div>');else{res.setHeader('Content-Type','text/javascript');res.end(await readFile(new URL('../frontend/'+req.url.slice(1),import.meta.url)));}}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;});
test.afterAll(()=>server.close());
async function setup(page,{team=true,pass=true,pending=false,maxRequests=3,supervisorFailure=false}={}){await page.goto(url);await page.evaluate(async({team,pass,pending,maxRequests,supervisorFailure})=>{const {mountAssistant}=await import('/assistant.js');window.settings={language:'en',model:'fixture',aiEnabled:true,aiTeamEnabled:team,maxRequests};window.requests=[];window.cancels=[];window.verifies=[];window.changes=[];window.doc={path:'C:/project/main.ag',text:'original'};window.ai=mountAssistant(document.querySelector('#assistant'),window.context={getSettings:()=>window.settings,getProjectRoot:()=> 'C:/project',getDocuments:()=>[window.doc],getDocument:()=>window.doc,listFiles:()=>['main.ag'],checkVerification:async()=>true,verifyProposal:async args=>{window.verifies.push(args);return{success:pass,compile:{success:pass},tests:[]};},updateDocument:async(path,text)=>window.changes.push(text),invoke:async(n,a)=>{if(n==='read_ai_file')return 'original';if(n==='cancel_api'){window.cancels.push(a.requestId);return;}if(n==='api_request'){window.requests.push(structuredClone(a));if(pending)return await new Promise(resolve=>(window.gates??=[]).push(resolve));const worker=a.body.instructions.includes('read-only reviewer');if(worker)return{status:'completed',output:[{type:'message',content:[{text:'independent report'}]}]};if(window.requests.filter(r=>!r.body.instructions.includes('read-only reviewer')).length===1)return{status:'completed',output:[{type:'function_call',name:'propose_file',arguments:JSON.stringify({path:'main.ag',content:'proposal'}),call_id:'p'}]};const supervisorRound=window.requests.filter(r=>!r.body.instructions.includes('read-only reviewer')).length;if(team&&supervisorRound===2){if(supervisorFailure)throw Error('Supervisor request failed');return{status:'completed',output:[{type:'function_call',name:'approve_proposal',arguments:JSON.stringify({decision:'approve',reason:'I independently checked the candidate reports and compiler evidence; no unresolved defect was demonstrated.'}),call_id:'a'}]};}return{status:'completed',output:[{type:'message',content:[{text:'Please review'}]}]};}throw Error(n);}});}, {team,pass,pending,maxRequests,supervisorFailure});await page.locator('.ai-share input').check();await page.locator('.ai-prompt').fill('improve');await page.locator('.ai-prompt').press('Enter');}
test('automatic team reviews before supervisor and proposal is independently verified before Apply',async({page})=>{await setup(page);await expect(page.getByRole('button',{name:'Apply proposal',exact:true})).toBeEnabled();const data=await page.evaluate(()=>({requests:window.requests,verifies:window.verifies,changes:window.changes}));expect(data.requests).toHaveLength(9);for(const r of data.requests.slice(0,3)){expect(r.body.tools.some(t=>['compile','propose_file','verify_proposal'].includes(t.name))).toBe(false);expect(r.body.instructions).toContain('Argent');}expect(data.verifies).toHaveLength(1);expect(data.changes).toHaveLength(0);await page.getByRole('button',{name:'Apply proposal',exact:true}).click();expect(await page.evaluate(()=>window.changes)).toEqual(['proposal']);});
test('failed local compilation blocks Apply',async({page})=>{await setup(page,{team:false,pass:false});await expect(page.getByLabel('Proposal',{exact:true})).toHaveValue('proposal');await expect.poll(()=>page.evaluate(()=>window.ai.isBusy())).toBe(false);await expect(page.getByRole('button',{name:'Apply proposal',exact:true})).toBeDisabled();expect(await page.evaluate(()=>window.changes.length)).toBe(0);});
test('Stop cancels all parallel request IDs and late responses cannot restore context',async({page})=>{await setup(page,{pending:true});await expect.poll(()=>page.evaluate(()=>window.requests.length)).toBe(3);await page.getByRole('button',{name:'Stop AI',exact:true}).click();await expect.poll(()=>page.evaluate(()=>window.cancels.length)).toBe(3);await page.evaluate(()=>window.gates.forEach(resolve=>resolve({status:'completed',output:[{type:'message',content:[{text:'PRIVATE LATE'}]}]})));await expect.poll(()=>page.evaluate(()=>window.ai.isBusy())).toBe(false);expect(await page.evaluate(()=>window.requests.length)).toBe(3);await expect(page.locator('.ai-transcript')).not.toContainText('PRIVATE LATE');});

test('exhausted worker budget blocks unreviewed proposal despite compiler success',async({page})=>{await setup(page,{maxRequests:1});await expect.poll(()=>page.evaluate(()=>window.ai.isBusy())).toBe(false);await expect(page.getByRole('button',{name:'Apply proposal',exact:true})).toBeDisabled();await page.getByRole('button',{name:'AI assistant',exact:true}).click();await expect(page.locator('.ai-transcript')).toContainText('Mandatory reviewer challenge incomplete');expect(await page.evaluate(()=>window.requests.length)).toBe(4);});

test('scenario tool delegates raw Int64 JSON to lossless parser and refuses absent parser',async({page})=>{await setup(page,{team:false});await expect.poll(()=>page.evaluate(()=>window.ai.isBusy())).toBe(false);const value=await page.evaluate(async()=>{window.context.parseScenarios=text=>{window.rawScenario=text;return[{scenario:{value:9223372036854775807n},expectedStatus:'failed'}];};await window.ai.executeTool('verify_proposal',{scenarios:'[{"scenario":{"value":9223372036854775807},"expectedStatus":"failed"}]'});const exact=window.verifies.at(-1).scenarios[0].scenario.value.toString();delete window.context.parseScenarios;let failure;try{await window.ai.executeTool('verify_proposal',{scenarios:'[{"value":9223372036854775807}]'});}catch(e){failure=e.message;}return{exact,raw:window.rawScenario,failure};});expect(value.exact).toBe('9223372036854775807');expect(value.raw).toContain('9223372036854775807');expect(value.failure).toContain('Lossless scenario parser unavailable');});

test('supervisor failure cannot release a compiled and worker-reviewed proposal',async({page})=>{await setup(page,{supervisorFailure:true});await expect.poll(()=>page.evaluate(()=>window.ai.isBusy())).toBe(false);await expect(page.getByRole('button',{name:'Apply proposal',exact:true})).toBeDisabled();expect(await page.evaluate(()=>window.verifies.length)).toBe(1);expect(await page.evaluate(()=>window.changes.length)).toBe(0);});
