import test from 'node:test';
import assert from 'node:assert/strict';
import {createCodeHistory} from '../frontend/code-history.js';
function setup(){const state={root:'C:/project',doc:{path:'C:/project/main.ag',text:'initial'},calls:[]};const history=createCodeHistory({getProjectRoot:()=>state.root,invoke:async(n,a)=>{state.calls.push({n,a});return[];}});return{state,history};}
test('queued checkpoints freeze root/path/text and never save project files',async()=>{const {state,history}=setup();const promise=history.checkpoint(state.doc,'saved');state.root='C:/other';state.doc.text='new';await promise;assert.deepEqual(state.calls[0],{n:'checkpoint_code_history',a:{projectRoot:'C:/project',path:'main.ag',text:'initial',reason:'saved'}});});
test('draft flush preserves last debounced edit on project switch',async()=>{const {state,history}=setup();history.schedule(state.doc);state.doc.text='final draft';history.schedule(state.doc);state.root='C:/other';history.projectChanged();await history.flush();assert.equal(state.calls.length,1);assert.equal(state.calls[0].a.text,'final draft');assert.equal(state.calls[0].a.projectRoot,'C:/project');});
test('generated and external documents have no checkpoints',async()=>{const {state,history}=setup();await history.checkpoint({...state.doc,generated:true});await history.checkpoint({...state.doc,path:'C:/external/main.ag'});await history.checkpoint({...state.doc,path:'C:/project/artifact.json'});assert.deepEqual(state.calls,[]);});
test('background storage failure settles without unhandled rejection and next write works',async()=>{let count=0;const {state}=setup();const history=createCodeHistory({getProjectRoot:()=>state.root,invoke:async()=>{if(!count++)throw Error('Disk full');return[];}});assert.equal(await history.checkpoint(state.doc),null);await history.flush();assert.deepEqual(await history.checkpoint(state.doc),[]);});
test('draft debounce keeps distinct files in the same project',async()=>{const {state,history}=setup();history.schedule(state.doc);history.schedule({path:'C:/project/lib.ag',text:'library draft'});await history.flush();assert.deepEqual(state.calls.map(c=>[c.a.path,c.a.text]),[['main.ag','initial'],['lib.ag','library draft']]);});
