import {test,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
test.use({browserName:process.env.ARGENT_BROWSER==='webkit'?'webkit':'chromium',channel:process.env.ARGENT_BROWSER==='webkit'?undefined:'msedge'});
let server,url;
test.beforeAll(async()=>{server=createServer(async(req,res)=>{try{if(req.url==='/')res.end('<html><body></body></html>');else{res.setHeader('Content-Type',req.url.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(new URL('../frontend/'+req.url.slice(1),import.meta.url)));}}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;});
test.afterAll(()=>server.close());
async function setup(page){await page.goto(url);await page.evaluate(async()=>{const link=document.createElement('link');link.rel='stylesheet';link.href='/code-history.css';document.head.append(link);const {createCodeHistory}=await import('/code-history.js');window.doc={path:'C:/project/main.ag',text:'current unsaved'};window.calls=[];window.historyUI=createCodeHistory({getSettings:()=>({language:'en'}),getProjectRoot:()=> 'C:/project',getDocument:()=>window.doc,updateDocument:(path,text,expected)=>{if(window.doc.text!==expected)return false;window.doc.text=text;window.calls.push({command:'editor',text});return true;},invoke:async(command,args)=>{window.calls.push({command,args});if(command==='checkpoint_code_history'){if(window.failCheckpoint)throw Error('Disk full');if(window.changeDuringCheckpoint)window.doc.text='new edit';return[];}if(command==='list_code_history')return[{id:'1',createdAt:1727900000000,reason:'saved',bytes:7}];if(command==='read_code_history')return 'old <script>window.executed=true</script>';throw Error(command);}});await window.historyUI.open(window.doc);});}
test('history preview renders source as text and restore preserves draft before editor-only update',async({page})=>{await setup(page);await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('.code-history-preview')).toContainText('current unsaved');await expect(page.locator('.code-history-preview')).toContainText('<script>window.executed=true</script>');expect(await page.evaluate(()=>window.executed)).toBeUndefined();await page.getByRole('button',{name:'Restore in editor'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);const calls=await page.evaluate(()=>window.calls);expect(calls.find(c=>c.command==='checkpoint_code_history').args).toMatchObject({text:'current unsaved',reason:'before-restore'});expect(calls.map(c=>c.command)).toEqual(['list_code_history','read_code_history','checkpoint_code_history','editor','checkpoint_code_history']);expect(await page.evaluate(()=>window.doc.text)).toContain('old <script>');});
test('failed checkpoint blocks restore and keeps current draft',async({page})=>{await setup(page);await page.evaluate(()=>window.failCheckpoint=true);await page.getByRole('button',{name:'Restore in editor'}).click();await expect(page.locator('.code-history-status')).toContainText('Disk full');expect(await page.evaluate(()=>window.doc.text)).toBe('current unsaved');expect(await page.evaluate(()=>window.calls.some(c=>c.command==='editor'))).toBe(false);});
test('concurrent edit during checkpoint blocks stale restore',async({page})=>{await setup(page);await page.evaluate(()=>window.changeDuringCheckpoint=true);await page.getByRole('button',{name:'Restore in editor'}).click();await expect(page.locator('.code-history-status')).toContainText('Editor changed');expect(await page.evaluate(()=>window.doc.text)).toBe('new edit');expect(await page.evaluate(()=>window.calls.some(c=>c.command==='editor'))).toBe(false);});


test('history translates owned errors but preserves unknown operating-system details',async({page})=>{
 await setup(page);
 await page.evaluate(async()=>{const {createCodeHistory}=await import('/code-history.js');document.querySelector('dialog')?.remove();const ui=createCodeHistory({getSettings:()=>({language:'de'}),getProjectRoot:()=> 'C:/project',getDocument:()=>window.doc,invoke:async()=>{throw Error('History entry no longer available');}});await ui.open(window.doc);});
 await expect(page.locator('.code-history-status')).toContainText('Dieser History-Eintrag ist nicht mehr verfügbar.');
});
