import {test,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
test.use({browserName:process.env.ARGENT_BROWSER==='webkit'?'webkit':'chromium',channel:process.env.ARGENT_BROWSER==='webkit'?undefined:'msedge'});
let server,url;
test.beforeAll(async()=>{server=createServer(async(req,res)=>{try{if(req.url==='/')res.end('<div id="assistant"></div>');else{res.setHeader('Content-Type','text/javascript');res.end(await readFile(new URL('../frontend/'+req.url.slice(1),import.meta.url)));}}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;});
test.afterAll(()=>server.close());
async function setup(page,{team=false,pass=true,pending=false,missing=false,declineInline=false}={}){await page.goto(url);await page.evaluate(async(options)=>{const {mountAssistant}=await import('/assistant.js');window.settings={language:'en',model:'fixture',aiEnabled:true,aiTeamEnabled:options.team,maxRequests:3};window.doc={path:'C:/project/main.ag',text:'original'};window.publications=[];window.changes=[];window.clearCount=0;window.round=0;window.root='C:/project';window.ai=mountAssistant(document.querySelector('#assistant'),{getSettings:()=>window.settings,getProjectRoot:()=>window.root,getDocuments:()=>options.missing?[]:[window.doc],getDocument:()=>options.missing?null:window.doc,listFiles:()=>options.missing?[]:['main.ag'],showProposal:p=>{window.inline=p;window.publications.push({path:p.path,before:p.before,after:p.after,ready:p.ready,busy:p.busy,message:p.message});return !options.declineInline;},clearProposal:()=>{window.inline=null;window.clearCount++;},checkVerification:async()=>true,verifyProposal:async()=>{if(options.pending)await new Promise(r=>window.finishVerify=r);return{success:options.pass,compile:{success:options.pass},tests:[]};},updateDocument:async(path,text,before,reason)=>{window.changes.push({path,text,before,reason});window.doc.text=text;},invoke:async(n,a)=>{if(n==='read_ai_file')return options.missing?null:'original';if(n==='cancel_api')return;if(n==='api_request'){if(a.body.instructions.includes('read-only reviewer'))return{status:'completed',output:[{type:'message',content:[{text:'Independent candidate review completed.'}]}]};window.round++;if(window.round===1)return{status:'completed',output:[{type:'function_call',name:'propose_file',arguments:JSON.stringify({path:'main.ag',content:'proposal'}),call_id:'p'}]};if(options.team&&window.round===2)return{status:'completed',output:[{type:'function_call',name:'approve_proposal',arguments:JSON.stringify({decision:'approve',reason:'Compiler evidence and all three independent candidate reports reviewed.'}),call_id:'a'}]};return{status:'completed',output:[]};}throw Error(n);}});},{team,pass,pending,missing,declineInline});await page.locator('.ai-share input').check();await page.locator('.ai-prompt').fill('improve');await page.locator('.ai-prompt').press('Enter');}
test('inline publication waits for full verification and supervisor, then applies atomically with history reason',async({page})=>{await setup(page,{team:true});await expect.poll(()=>page.evaluate(()=>window.inline?.ready)).toBe(true);await expect(page.locator('.ai-chat-page')).toBeVisible();await expect(page.getByLabel('Proposal',{exact:true})).toBeHidden();const items=await page.evaluate(()=>window.publications);expect(items[0]).toMatchObject({path:'C:/project/main.ag',before:'original',after:'proposal',ready:false,busy:true});expect(items.filter(x=>x.ready)).toHaveLength(1);expect(items.at(-1).message).toContain('supervisor approved');expect(await page.evaluate(()=>window.changes)).toEqual([]);await page.evaluate(()=>window.inline.onApply());expect(await page.evaluate(()=>window.changes)).toEqual([{path:'C:/project/main.ag',text:'proposal',before:'original',reason:'ai'}]);expect(await page.evaluate(()=>window.inline)).toBeNull();});
test('pending and failed verification cannot apply through editor callbacks',async({page})=>{await setup(page,{pending:true,pass:false});await expect.poll(()=>page.evaluate(()=>!!window.finishVerify)).toBe(true);await page.evaluate(()=>window.inline.onApply());expect(await page.evaluate(()=>window.changes)).toEqual([]);await page.evaluate(()=>window.finishVerify());await expect.poll(()=>page.evaluate(()=>window.ai.isBusy())).toBe(false);expect(await page.evaluate(()=>window.inline.ready)).toBe(false);await page.evaluate(()=>window.inline.onApply());expect(await page.evaluate(()=>window.changes)).toEqual([]);});
test('callbacks from discarded proposals cannot apply or discard their replacement',async({page})=>{await setup(page);await expect.poll(()=>page.evaluate(()=>window.inline?.ready)).toBe(true);await page.evaluate(()=>{window.old=window.inline;window.inline.onDiscard();window.round=0;});await page.locator('.ai-prompt').fill('again');await page.locator('.ai-prompt').press('Enter');await expect.poll(()=>page.evaluate(()=>window.inline?.ready)).toBe(true);await page.evaluate(async()=>{await window.old.onApply();window.old.onDiscard();});expect(await page.evaluate(()=>window.changes)).toEqual([]);expect(await page.evaluate(()=>window.inline.after)).toBe('proposal');await page.evaluate(()=>window.inline.onApply());expect(await page.evaluate(()=>window.changes.length)).toBe(1);});
test('editor callback rechecks live buffer and revocation clears inline proposal',async({page})=>{await setup(page);await expect.poll(()=>page.evaluate(()=>window.inline?.ready)).toBe(true);await page.evaluate(async()=>{window.doc.text='manual edit';await window.inline.onApply();});expect(await page.evaluate(()=>window.changes)).toEqual([]);expect(await page.evaluate(()=>window.inline.ready)).toBe(false);await page.evaluate(()=>{window.settings.aiEnabled=false;window.ai.refresh();});expect(await page.evaluate(()=>window.inline)).toBeNull();});
test('new files and editor refusal retain accessible legacy full preview',async({page})=>{for(const options of [{missing:true},{declineInline:true}]){await setup(page,options);await expect(page.getByLabel('Proposal',{exact:true})).toBeVisible();await expect(page.getByLabel('Proposal',{exact:true})).toHaveValue('proposal');await expect(page.getByRole('button',{name:'Apply proposal',exact:true})).toBeEnabled();}});
test('project switch and disposal clear proposals and invalidate retained callbacks',async({page})=>{await setup(page);await expect.poll(()=>page.evaluate(()=>window.inline?.ready)).toBe(true);await page.evaluate(async()=>{const old=window.inline;window.root='C:/different';window.ai.projectChanged();await old.onApply();old.onDiscard();window.ai.dispose();});expect(await page.evaluate(()=>window.inline)).toBeNull();expect(await page.evaluate(()=>window.changes)).toEqual([]);expect(await page.evaluate(()=>window.clearCount)).toBeGreaterThanOrEqual(2);});
