import {test,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
test.use({browserName:process.env.ARGENT_BROWSER==='webkit'?'webkit':'chromium',channel:process.env.ARGENT_BROWSER==='webkit'?undefined:'msedge'});
let server,url;
test.beforeAll(async()=>{server=createServer(async(req,res)=>{try{if(req.url==='/')res.end('<div id="assistant"></div>');else{res.setHeader('Content-Type','text/javascript');res.end(await readFile(new URL('../frontend/'+req.url.slice(1),import.meta.url)));}}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;});
test.afterAll(()=>server.close());
const call=(name,args)=>({type:'function_call',name,arguments:JSON.stringify(args),call_id:Math.random().toString()});
const message=text=>({type:'message',content:[{text}]});
async function setup(page){await page.goto(url);await page.evaluate(async()=>{const {mountAssistant}=await import('/assistant.js');window.doc={path:'C:/project/main.ag',text:'original'};window.settings={language:'en',model:'fixture',aiEnabled:true,aiTeamEnabled:true,maxRequests:5};window.requests=[];window.verifies=[];window.changes=[];window.previews=[];window.plan=[];window.context={getSettings:()=>window.settings,getProjectRoot:()=> 'C:/project',getDocuments:()=>[window.doc],getDocument:()=>window.doc,listFiles:()=>['main.ag'],showProposal:p=>{window.previews.push(p);window.preview=p;return true;},clearProposal:()=>{window.preview=null;},checkVerification:async()=>true,verifyProposal:async args=>{window.verifies.push(args);return{success:true,compile:{success:true},tests:args.scenarios};},updateDocument:async(path,text)=>window.changes.push(text),invoke:async(n,a)=>{if(n==='read_ai_file')return window.doc.text;if(n==='cancel_api')return;if(n==='api_request'){window.requests.push(structuredClone(a));if(a.body.instructions.includes('read-only reviewer'))return{status:'completed',output:[{type:'message',content:[{text:'fresh report '+window.verifies.length}]}]};const output=window.plan.shift();if(output==='FAIL')throw Error('fixture failure');if(output==='WAIT')return await new Promise(resolve=>window.release=resolve);return{status:'completed',output:output||[{type:'message',content:[{text:'done'}]}]};}throw Error(n);}};window.ai=mountAssistant(document.querySelector('#assistant'),window.context);});await page.locator('.ai-share input').check();}
async function send(page,plan,text='follow up'){await page.evaluate(p=>window.plan=p,plan);await page.locator('.ai-prompt').fill(text);await page.locator('.ai-prompt').press('Enter');await expect.poll(()=>page.evaluate(()=>window.ai.isBusy())).toBe(false);}
async function propose(page,decision='reject'){await send(page,[[call('propose_file',{path:'main.ag',content:'candidate'})],[call('approve_proposal',{decision,reason:decision==='reject'?'VM signature cases missing':'Independent proof accepted'})],[message('preview')]],'improve');}
test('rejected pending preview permits questions with bounded unapplied candidate context',async({page})=>{await setup(page);await propose(page);const count=await page.evaluate(()=>window.verifies.length);await send(page,[[message('reason explained')]],'why rejected?');await expect(page.locator('.ai-transcript')).toContainText('reason explained');const value=await page.evaluate(()=>({text:JSON.stringify(window.requests.at(-1).body.input),changes:window.changes,preview:window.preview,checks:window.verifies.length}));expect(value.text).toContain('PENDING UNAPPLIED PREVIEW');expect(value.text).toContain('VM signature cases missing');expect(value.text).toContain('candidate');expect(value.checks).toBe(count);expect(value.changes).toEqual([]);expect(value.preview.ready).toBe(false);expect(value.preview.message).toContain('supervisor rejected');});
test('same-file revision receives fresh independent reports and old inline Apply cannot apply replacement',async({page})=>{await setup(page);await propose(page,'approve');await page.evaluate(()=>window.oldApply=window.preview.onApply);await send(page,[[call('propose_file',{path:'main.ag',content:'revised'})],[call('approve_proposal',{decision:'approve',reason:'Fresh reviews and local checks accepted'})],[message('revised')]],'revise it');const value=await page.evaluate(()=>({checks:window.verifies.length,text:window.preview.after,ready:window.preview.ready,reviews:window.requests.filter(r=>r.body.instructions.includes('read-only reviewer')).map(r=>JSON.stringify(r.body.input))}));expect(value.checks).toBe(2);expect(value.text).toBe('revised');expect(value.ready).toBe(true);expect(value.reviews.filter(r=>r.includes('revised'))).toHaveLength(3);await page.evaluate(()=>window.oldApply());expect(await page.evaluate(()=>window.changes)).toEqual([]);await page.evaluate(()=>window.preview.onApply());expect(await page.evaluate(()=>window.changes)).toEqual(['revised']);});
test('approved pending preview permits questions without source edits or additional verification',async({page})=>{await setup(page);await propose(page,'approve');await send(page,[[message('explanation')]],'explain');expect(await page.evaluate(()=>({changes:window.changes,checks:window.verifies.length,ready:window.preview.ready}))).toEqual({changes:[],checks:1,ready:true});});
test('explicit pending VM verification requires fresh reviewers before supervisor approval',async({page})=>{await setup(page);await propose(page);await send(page,[[call('verify_proposal',{scenarios:'[]'})],[call('approve_proposal',{decision:'approve',reason:'New tests and fresh reviewers checked'})],[message('approved')]],'test pending candidate');expect(await page.evaluate(()=>({checks:window.verifies.length,ready:window.preview.ready,reviewers:window.requests.filter(r=>r.body.instructions.includes('read-only reviewer')).length}))).toEqual({checks:2,ready:true,reviewers:12});});
test('different-file proposal preserves pending candidate and chat continues',async({page})=>{await setup(page);await propose(page);await send(page,[[call('propose_file',{path:'other.ag',content:'other'})],[message('need discard before other file')]],'other file');expect(await page.evaluate(()=>window.preview.after)).toBe('candidate');await expect(page.locator('.ai-transcript')).toContainText('need discard before other file');expect(await page.evaluate(()=>window.changes)).toEqual([]);});
test('source changed since fresh read cannot replace pending candidate',async({page})=>{await setup(page);await propose(page);await page.evaluate(()=>window.doc.text='updated');await send(page,[[message('current source acknowledged')]],'explain');await page.evaluate(()=>window.doc.text='newer');const failure=await page.evaluate(async()=>{try{await window.ai.executeTool('propose_file',{path:'main.ag',content:'stale revision'});}catch(e){return e.message;}});expect(failure).toContain('Source changed since read');expect(await page.evaluate(()=>window.preview.after)).toBe('candidate');expect(await page.evaluate(()=>window.changes)).toEqual([]);});
test('failed follow-up revokes approved Apply and retains candidate for recovery',async({page})=>{await setup(page);await propose(page,'approve');await send(page,['FAIL'],'check more');expect(await page.evaluate(()=>({ready:window.preview.ready,text:window.preview.after,changes:window.changes}))).toEqual({ready:false,text:'candidate',changes:[]});});
test('busy and cancelled follow-up cannot apply previously approved preview',async({page})=>{await setup(page);await propose(page,'approve');await page.evaluate(()=>window.oldApply=window.preview.onApply);await page.evaluate(()=>window.plan=['WAIT']);await page.locator('.ai-prompt').fill('more detail');await page.locator('.ai-prompt').press('Enter');await expect.poll(()=>page.evaluate(()=>!!window.release)).toBe(true);expect(await page.evaluate(()=>window.preview.ready)).toBe(false);await page.evaluate(()=>window.oldApply());expect(await page.evaluate(()=>window.changes)).toEqual([]);await page.getByRole('button',{name:'Stop AI',exact:true}).click();await page.evaluate(()=>window.release({status:'completed',output:[{type:'message',content:[{text:'late'}]}]}));await expect.poll(()=>page.evaluate(()=>window.ai.isBusy())).toBe(false);expect(await page.evaluate(()=>window.preview.ready)).toBe(false);});
