import {test} from 'node:test';
import assert from 'node:assert/strict';
import {normalizeReviewFindings,REVIEW_LIMITS} from '../frontend/review-findings.js';
const text='first\nsecond\nthird';const note={startLine:2,endLine:3,title:'Check',message:'Review explanation'};
const payload=findings=>({before:text,findings});
test('review notes preserve explicit ranges and optional plain code without editing source',()=>{const result=normalizeReviewFindings(payload([{...note,suggestion:'<img onerror=boom>'}]),text);assert.deepEqual(result.findings[0],{...note,suggestion:'<img onerror=boom>'});assert.equal(result.before,text);});
test('stale, readonly, absent and malformed reviews are rejected; empty clears accepted',()=>{assert.equal(normalizeReviewFindings(payload([note]),'changed'),null);assert.equal(normalizeReviewFindings(payload([note]),text,true),null);assert.equal(normalizeReviewFindings(null,text),null);assert.equal(normalizeReviewFindings({before:text,findings:'bad'},text),null);assert.deepEqual(normalizeReviewFindings(payload([]),text).findings,[]);assert.equal(normalizeReviewFindings({...payload([note]),before:text.replaceAll('\n','\r\n')},text).before,text);});
test('explicit line ranges never silently clamp or infer locations',()=>{for(const range of [{startLine:0},{endLine:4},{startLine:3,endLine:2},{startLine:1.5},{endLine:NaN},{startLine:'2'},{endLine:undefined}])assert.equal(normalizeReviewFindings(payload([{...note,...range}]),text),null);});
test('review payload strings, counts and aggregate lengths are bounded',()=>{assert.equal(normalizeReviewFindings(payload(Array(33).fill(note)),text),null);for(const item of [{title:''},{message:' '},{suggestion:123},{title:'x'.repeat(201)},{message:'x'.repeat(4001)},{suggestion:'x'.repeat(16001)}])assert.equal(normalizeReviewFindings(payload([{...note,...item}]),text),null);assert.equal(normalizeReviewFindings(payload(Array(20).fill({...note,message:'x'.repeat(4000)})),text),null);assert.equal(REVIEW_LIMITS.findings,32);});
test('callbacks are preserved only when callable',()=>{const callback=()=>{};assert.equal(normalizeReviewFindings({...payload([note]),onRequestProposal:callback},text).onRequestProposal,callback);assert.equal(normalizeReviewFindings({...payload([note]),onRequestProposal:'bad'},text).onRequestProposal,undefined);});

test('optional original anchors must match exact normalized range and remain bounded',()=>{assert.equal(normalizeReviewFindings(payload([{...note,original:'wrong'}]),text),null);assert.equal(normalizeReviewFindings(payload([{...note,original:'second\r\nthird'}]),text).findings[0].original,'second\nthird');assert.equal(normalizeReviewFindings(payload([{...note,original:42}]),text),null);});
