import {test,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
test.use({browserName:process.env.ARGENT_BROWSER==='webkit'?'webkit':'chromium',channel:process.env.ARGENT_BROWSER==='webkit'?undefined:'msedge'});
let server,url;
test.beforeAll(async()=>{server=createServer(async(req,res)=>{try{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end('<div id="assistant"></div>');}else{res.setHeader('Content-Type','text/javascript');res.end(await readFile(new URL('../frontend/'+req.url.slice(1),import.meta.url)));}}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;});
test.afterAll(()=>server.close());
async function mount(page){await page.goto(url);await page.evaluate(async()=>{const {mountAssistant}=await import('/assistant.js');window.settings={language:'en',model:'fixture',maxRequests:1,aiEnabled:true};window.root='C:/project';window.doc={path:'C:/project/tickets.ag',text:'first\nsecond\nthird',generated:false};window.markers=[];window.requests=[];window.nativeReads=[];window.clearCount=0;window.acceptMarkers=true;window.responseIndex=0;window.responses=[];window.ai=mountAssistant(document.querySelector('#assistant'),{getSettings:()=>window.settings,getProjectRoot:()=>window.root,getDocuments:()=>[window.doc],getDocument:()=>window.doc,listFiles:()=>['tickets.ag'],markReview:args=>{if(!window.acceptMarkers)return false;window.markers.push(args);return true;},clearReviews:()=>{window.clearCount++;window.markers=[];},invoke:async(n,a)=>{if(n==='read_ai_file'){window.nativeReads.push(a);if(window.readFailure)throw Error('Native scope rejected');return window.doc.text;}if(n==='api_request'){window.requests.push(structuredClone(a));return window.responses[window.responseIndex++]||{status:'completed',output:[]};}if(n==='cancel_api')return;throw Error('Forbidden unexpected tool '+n);},updateDocument:()=>{throw Error('Review must not edit source');}});window.findings=JSON.stringify([{startLine:2,endLine:2,title:'Check authorization',message:'Review this condition.',suggestion:'Clarify the intended authorization policy.'}]);});await page.locator('.ai-share input').check();}
async function tool(page,name,args,readonly=false){return await page.evaluate(async({name,args,readonly})=>{try{return{ok:true,result:await window.ai.executeTool(name,args,readonly)};}catch(e){return{ok:false,error:e.message};}},{name,args,readonly});}
test('review markers require a native scoped read and display exact bounded editor findings without source writes',async({page})=>{await mount(page);let findings=await page.evaluate(()=>window.findings);expect((await tool(page,'mark_review',{path:'tickets.ag',findings})).error).toContain('Read this file');expect((await tool(page,'read_file',{path:'tickets.ag'})).ok).toBe(true);const marked=await tool(page,'mark_review',{path:'tickets.ag',findings});expect(marked.result).toMatchObject({displayed:true,path:'tickets.ag',count:1});expect(await page.evaluate(()=>window.markers[0])).toMatchObject({path:'C:/project/tickets.ag',before:'first\nsecond\nthird',findings:[{startLine:2,endLine:2,title:'Check authorization'}]});expect(await page.evaluate(()=>window.doc.text)).toBe('first\nsecond\nthird');expect(await page.evaluate(()=>window.nativeReads.length)).toBe(2);expect(await page.evaluate(()=>window.requests.length)).toBe(0);});
test('stale source, invalid range, readonly worker and failed editor display cannot report success',async({page})=>{await mount(page);const findings=await page.evaluate(()=>window.findings);await tool(page,'read_file',{path:'tickets.ag'});await page.evaluate(()=>window.doc.text+='\nchanged');expect((await tool(page,'mark_review',{path:'tickets.ag',findings})).error).toContain('Source changed');await tool(page,'read_file',{path:'tickets.ag'});const invalid=JSON.stringify([{startLine:1,endLine:99,title:'Bad',message:'Invalid range'}]);expect((await tool(page,'mark_review',{path:'tickets.ag',findings:invalid})).error).toContain('Invalid review');expect((await tool(page,'mark_review',{path:'tickets.ag',findings},true)).error).toContain('Read-only');await page.evaluate(()=>window.acceptMarkers=false);expect((await tool(page,'mark_review',{path:'tickets.ag',findings})).error).toContain('not displayed');await page.evaluate(()=>window.readFailure=true);expect((await tool(page,'mark_review',{path:'tickets.ag',findings})).error).toContain('Native scope rejected');expect(await page.evaluate(()=>window.markers)).toEqual([]);});
test('new chat, consent revocation, project change and disposal clear existing markers',async({page})=>{await mount(page);const findings=await page.evaluate(()=>window.findings);await tool(page,'read_file',{path:'tickets.ag'});await tool(page,'mark_review',{path:'tickets.ag',findings});await page.getByRole('button',{name:'New chat',exact:true}).click();expect(await page.evaluate(()=>window.markers)).toEqual([]);await tool(page,'read_file',{path:'tickets.ag'});await tool(page,'mark_review',{path:'tickets.ag',findings});await page.locator('.ai-share input').uncheck();expect((await tool(page,'mark_review',{path:'tickets.ag',findings})).error).toMatch(/disabled|Cancelled/);await page.evaluate(()=>{window.root='C:/different';window.ai.projectChanged();window.ai.dispose();});expect(await page.evaluate(()=>window.clearCount)).toBeGreaterThanOrEqual(4);});
test('text-only review receives one bounded corrective mark_review request and actual markers',async({page})=>{await mount(page);await page.evaluate(()=>{window.settings.maxRequests=2;window.responses=[{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'The second line requires an authorization check. I cannot mark the editor.'}]}]},{status:'completed',output:[{type:'function_call',name:'mark_review',arguments:JSON.stringify({path:'tickets.ag',findings:window.findings}),call_id:'mark'}]}];});await page.locator('.ai-prompt').fill('Prüfe tickets.ag und markiere die Befunde im Editor.');await page.locator('.ai-prompt').press('Enter');await expect.poll(()=>page.evaluate(()=>window.ai.isBusy())).toBe(false);expect(await page.evaluate(()=>window.requests.length)).toBe(2);expect(await page.evaluate(()=>window.requests[1].body.tool_choice)).toEqual({type:'function',name:'mark_review'});expect(await page.evaluate(()=>window.markers.length)).toBe(1);await expect(page.locator('.ai-transcript')).not.toContainText('I cannot mark');await expect(page.locator('.ai-transcript')).toContainText('1 review findings updated in the editor');});
test('unshared and explain-only requests do not get review correction or code tools',async({page})=>{await mount(page);await page.locator('.ai-share input').uncheck();await page.evaluate(()=>{window.responses=[{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Review concepts.'}]}]}];});await page.evaluate(()=>window.ai.requestChange('Review concepts'));expect(await page.evaluate(()=>window.requests.length)).toBe(1);expect(await page.evaluate(()=>window.requests[0].body.tools.some(x=>x.name==='mark_review'))).toBe(false);await page.locator('.ai-share input').check();await page.evaluate(()=>{window.responses.push({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'The second line contains code.'}]}]});return window.ai.explain('Prüfe die Datei');});expect(await page.evaluate(()=>window.requests.length)).toBe(2);expect(await page.evaluate(()=>window.requests[1].body.tools)).toEqual([]);});
test('empty findings report zero honestly and budget exhaustion cannot add an API request',async({page})=>{await mount(page);await tool(page,'read_file',{path:'tickets.ag'});expect((await tool(page,'mark_review',{path:'tickets.ag',findings:'[]'})).result).toMatchObject({displayed:true,count:0});await page.evaluate(()=>{window.responses=[{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'The source needs improvement.'}]}]}];});await page.evaluate(()=>window.ai.requestChange('Prüfe tickets.ag'));expect(await page.evaluate(()=>window.requests.length)).toBe(1);await expect(page.locator('.ai-transcript')).toContainText('No editor markers created: request limit reached');});

test('a source snapshot is bound to its project even with identical source in another project',async({page})=>{await mount(page);const findings=await page.evaluate(()=>window.findings);await tool(page,'read_file',{path:'tickets.ag'});await page.evaluate(()=>{window.root='C:/another-project';window.doc.path='C:/another-project/tickets.ag';});expect((await tool(page,'mark_review',{path:'tickets.ag',findings})).error).toContain('Read this file');expect(await page.evaluate(()=>window.markers.length)).toBe(0);});

test('source anchors reject wrong lines and review payload has a combined size bound',async({page})=>{await mount(page);await tool(page,'read_file',{path:'tickets.ag'});const anchored={startLine:2,endLine:2,title:'Anchor',message:'Finding',original:'wrong'};expect((await tool(page,'mark_review',{path:'tickets.ag',findings:JSON.stringify([anchored])})).error).toContain('Invalid review');anchored.original='second';expect((await tool(page,'mark_review',{path:'tickets.ag',findings:JSON.stringify([anchored])})).result.count).toBe(1);const excessive=Array.from({length:5},()=>({startLine:1,endLine:1,title:'Large',message:'Message',suggestion:'x'.repeat(16000)}));expect((await tool(page,'mark_review',{path:'tickets.ag',findings:JSON.stringify(excessive)})).error).toContain('payload size');expect((await tool(page,'mark_review',{path:'tickets.ag',findings:'[]'})).result.message).toContain('No findings supplied; review markers cleared');});
