import {test,expect} from '@playwright/test';
import {createServer} from 'vite';
test.setTimeout(20000);test.use({browserName:process.env.ARGENT_BROWSER==='webkit'?'webkit':'chromium',channel:process.env.ARGENT_BROWSER==='webkit'?undefined:'msedge'});let server,url;
test.beforeAll(async()=>{server=await createServer({configFile:false,root:process.cwd(),server:{host:'127.0.0.1',port:0,watch:null},plugins:[{name:'review-harness',configureServer(vite){vite.middlewares.use((req,res,next)=>{if(req.url==='/review-harness'){res.setHeader('Content-Type','text/html');res.end('<html><body><div id="editor" style="height:600px;width:900px"></div></body></html>');}else next();});}}]});await server.listen();url=server.resolvedUrls.local[0]+'review-harness';});
test.afterAll(async()=>{await server?.close();});
async function open(page){await page.goto(url);await page.evaluate(async()=>{const {createEditor}=await import('/frontend/editor.js');window.calls=[];window.settings={language:'en'};window.editor=createEditor(document.querySelector('#editor'),{text:'first\nsecond\nthird\nlast',getSettings:()=>window.settings});window.review={before:window.editor.getText(),findings:[{startLine:2,endLine:3,title:'Check authorization',message:'Consider a policy check',suggestion:'<img src=x onerror=alert(1)>'}],onRequestProposal:note=>window.calls.push(note)};window.accepted=window.editor.setReviews(window.review);});}
test('actual review notes mark code and expose keyboard accessible unverified preview without direct apply',async({page})=>{await open(page);await expect(page.locator('.cm-ai-review')).toHaveCount(2);const marker=page.getByRole('button',{name:'Show AI review note'});await marker.focus();await marker.press('Enter');const dialog=page.getByRole('dialog',{name:'AI review note'});await expect(dialog).toBeVisible();await expect(dialog.locator('pre').first()).toHaveText('second\nthird');await expect(dialog.locator('pre').last()).toHaveText('<img src=x onerror=alert(1)>');await expect(dialog.locator('img')).toHaveCount(0);await expect(dialog).toContainText('Suggested code (unverified)');await expect(dialog.getByRole('button',{name:'Apply all changes'})).toHaveCount(0);await dialog.getByRole('button',{name:'Prepare change'}).press('Enter');expect(await page.evaluate(()=>window.calls[0].startLine)).toBe(2);expect(await page.evaluate(()=>window.editor.getText())).toBe('first\nsecond\nthird\nlast');await dialog.getByRole('button',{name:'Close',exact:true}).press('Escape');await expect(dialog).toHaveCount(0);});
test('hover, language and dark mode refresh work; edit, clear and readonly remove visible review',async({page})=>{await open(page);await page.locator('.cm-ai-review').first().hover({position:{x:12,y:10}});await expect(page.getByRole('dialog')).toBeVisible();await page.evaluate(()=>window.editor.clearReviews());await expect(page.getByRole('dialog')).toHaveCount(0);await page.evaluate(()=>{window.editor.setReviews(window.review);window.settings={language:'de',darkMode:true};window.editor.refresh();});await page.getByRole('button',{name:'KI-Prüfhinweis anzeigen'}).click();await expect(page.getByRole('dialog',{name:'KI-Prüfhinweis'})).toBeVisible();await expect(page.locator('.cm-ai-tooltip-dark')).toHaveCount(1);await page.evaluate(()=>window.editor.view.dispatch({changes:{from:0,insert:'x'}}));await expect(page.locator('.cm-ai-review')).toHaveCount(0);await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>window.editor.setReviews(window.review))).toBe(false);await page.evaluate(()=>{window.editor.setText(window.review.before);window.editor.setReviews(window.review);window.editor.setReadOnly(true);});await expect(page.locator('.cm-ai-review')).toHaveCount(0);expect(await page.evaluate(()=>window.editor.setReviews(window.review))).toBe(false);});
test('validated proposal wins overlap while both independent annotations remain',async({page})=>{await open(page);await page.evaluate(()=>window.editor.setProposal({before:window.review.before,after:'first\nnew\nthird\nlast',ready:true}));await expect(page.locator('.cm-ai-review')).toHaveCount(2);await expect(page.locator('.cm-ai-change')).toHaveCount(1);await page.locator('.cm-ai-change').hover({position:{x:12,y:10}});await expect(page.getByRole('dialog',{name:'AI code suggestion'})).toBeVisible();await expect(page.getByRole('dialog',{name:'AI review note'})).toHaveCount(0);await page.evaluate(()=>window.editor.clearProposal());await expect(page.locator('.cm-ai-review')).toHaveCount(2);});
