import {test,expect} from '@playwright/test';
import {createServer} from 'vite';
import {createRequire} from 'node:module';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
const {structure}=createRequire(import.meta.url)('../resources/assets/language/structure-service.js');
let server,url;
test.beforeAll(async()=>{await mkdir(new URL('../qa/',import.meta.url),{recursive:true});server=await createServer({server:{host:'127.0.0.1',port:1451,strictPort:false,hmr:false,watch:null},logLevel:'error'});await server.listen();url=server.resolvedUrls.local[0];});
test.afterAll(async()=>server?.close());
test.use({browserName:process.env.ARGENT_BROWSER==='webkit'?'webkit':'chromium',channel:process.env.ARGENT_BROWSER==='webkit'?undefined:'msedge',viewport:{width:1600,height:1000}});
test('ticket network expands source groups, explains typed edges, edits exact code and switches language',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const text=await readFile(new URL('../resources/examples/catalog/tickets/tickets.ag',import.meta.url),'utf8');
 await page.exposeFunction('analyzeStructure',structure);await page.route('**/*',route=>route.request().resourceType()==='document'?route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><link rel="stylesheet" href="/frontend/style.css"><link rel="stylesheet" href="/frontend/structure.css"></head><body></body></html>'}):route.continue());await page.goto(url);
 const fixturePath=path.resolve('test-output/network-fixture/Prüfung/tickets.ag');
 await page.evaluate(async ({text,fixturePath})=>{
  document.body.innerHTML='<div id="network-test" style="width:1550px;height:950px"></div>';
  document.documentElement.dataset.theme='dark';
  const {mountStructure}=await import('/frontend/structure.js');
  window.settings={language:'de'};window.docs=[{path:fixturePath,text}];
  window.structure=mountStructure(document.querySelector('#network-test'),{getDocument:()=>docs[0],getDocuments:()=>docs,getSettings:()=>settings,invoke:(_,{request})=>window.analyzeStructure(request),updateDocument:(path,text)=>{docs.find(d=>d.path===path).text=text;},openFile:(path,start)=>{window.opened={path,start};},notify:message=>{window.notice=message;}});
 },{text,fixturePath});
 await expect(page.locator('.structure-card').first()).toBeVisible();
 await expect(page.locator('.structure-toggle')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Blockdetails',exact:true})).toHaveCount(0);
 const appCard=page.locator('.structure-card[data-kind="app"]');
 const issuerCard=page.locator('.structure-card[data-kind="actor"]').filter({hasText:'Issuer'});
 await expect(appCard).toHaveCount(1);
 await expect(page.locator('.structure-card[data-kind="actor"]')).toHaveCount(2);
 await expect(issuerCard).toHaveAttribute('aria-expanded','false');
 await page.screenshot({path:'qa/rule-network-actor-groups.png'});
 await issuerCard.dblclick({delay:150});
 await expect(issuerCard).toHaveAttribute('aria-expanded','true');
 const issueCard=page.locator('.structure-card[data-kind="entry"]').filter({hasText:'issue'});
 await expect(issueCard).toHaveAttribute('aria-expanded','false');
 await issueCard.dblclick({delay:150});
 await expect(issueCard).toHaveAttribute('aria-expanded','true');
 await appCard.dblclick();
 await expect(page.locator('.structure-card')).toHaveCount(1);
 await appCard.dblclick();
 await expect(issuerCard).toHaveAttribute('aria-expanded','true');
 await expect(issueCard).toHaveAttribute('aria-expanded','true');
 await page.getByRole('button',{name:'Alles einpassen',exact:true}).click();
 await expect.poll(()=>page.locator('.structure-edge[data-kind="value"]').count()).toBeGreaterThan(1);
 const actionRow=page.locator('.structure-tree-row').filter({hasText:'Aktion · issue'});
 await actionRow.dblclick();
 await expect(actionRow).toHaveAttribute('aria-expanded','false');
 await actionRow.dblclick();
 await expect(actionRow).toHaveAttribute('aria-expanded','true');
 const appRow=page.locator('.structure-tree-row').filter({hasText:'App · Tickets'});
 await appRow.dblclick();
 await expect(appRow).toHaveAttribute('aria-expanded','false');
 await appRow.dblclick();
 await expect(appRow).toHaveAttribute('aria-expanded','true');
 await actionRow.click();
 const before=await page.locator('.structure-card').count();
 const group=page.locator('.structure-card').filter({hasText:'new_ticket'}).first();
 await page.locator('.structure-fragment').focus();
 // A human double-click leaves enough time for asynchronous focus-out handlers.
 await group.dblclick({delay:150});
 await expect.poll(()=>page.locator('.structure-card').count()).toBeGreaterThan(before);
 await group.dblclick();
 await expect(page.locator('.structure-card')).toHaveCount(before);
 await group.dblclick();
 await expect.poll(()=>page.locator('.structure-card').count()).toBeGreaterThan(before);
 await group.dblclick();
 await expect(page.locator('.structure-card')).toHaveCount(before);
 await group.dblclick();
 await expect.poll(()=>page.locator('.structure-card').count()).toBeGreaterThan(before);
 await page.getByRole('button',{name:'Alles einpassen',exact:true}).click();
 await page.screenshot({path:'qa/rule-network-ticket-expanded-de.png'});
 // Inspect source spans instead of assuming labels identify a rule uniquely.
 const id=await page.evaluate(()=>window.structure.getModel().flow.nodes.find(n=>n.kind==='check'&&n.text.includes('ticket.value > 0')).id);
 const check=page.locator('.structure-card').filter({has:page.locator('title')}).filter({hasText:'ticket.value'}).first();
 await page.locator('.structure-card').evaluateAll((cards,id)=>cards.find(c=>c.dataset.nodeId===id)?.dispatchEvent(new MouseEvent('click',{bubbles:true})),id);
 await expect(page.locator('.structure-fragment')).toHaveValue(/require\(ticket.value > 0\)/);
 await page.locator('.structure-fragment').fill('require(ticket.value > 1);');
 await expect.poll(()=>page.evaluate(()=>docs[0].text)).toContain('require(ticket.value > 1);');
 await page.locator('.structure-heading').click();
 await page.getByRole('button',{name:'Struktur aktualisieren',exact:true}).click();
 await page.getByRole('button',{name:'Alles einpassen',exact:true}).click();
 const edge=page.locator('.structure-edge[data-kind="value"] .structure-edge-hit').first();
 await edge.dispatchEvent('pointerenter',{clientX:400,clientY:300});
 await edge.dispatchEvent('click');
 await expect(page.locator('.structure-edge-info')).toContainText('Datentyp:');
 const hoverCard=page.locator('.structure-card[data-kind="check"]').first();
 await hoverCard.dispatchEvent('pointerenter');
 const hoverId=await hoverCard.getAttribute('data-node-id');
 const expected=await page.evaluate(id=>structure.getNetwork().edges.filter(e=>e.from===id||e.to===id).length,hoverId);
 await expect(page.locator('.structure-edge.highlighted')).toHaveCount(expected);
 expect(expected).toBeGreaterThan(0);
 await expect.poll(()=>page.locator('.structure-edge:not(.highlighted)').first().evaluate(e=>Number(getComputedStyle(e).opacity))).toBeLessThan(.3);
 await hoverCard.dispatchEvent('pointerleave');
 await expect(page.locator('.structure-edge.highlighted')).toHaveCount(1);
 await expect(page.locator('.structure-edge-info')).toContainText('Datentyp:');
 expect(await page.locator('.structure-group-envelope').first().evaluate(e=>getComputedStyle(e).strokeWidth)).toBe('2px');
 const sourcePaths=await page.locator('.structure-card title').allTextContents();
 expect(sourcePaths.some(s=>s.replaceAll('\\','/').includes(fixturePath.replaceAll('\\','/')))).toBe(false);
 await page.evaluate(()=>{settings.language='en';structure.refreshSettings();});
 await expect(page.getByRole('button',{name:'Fit all',exact:true})).toBeVisible();
 await expect(page.locator('.structure-edge-info')).toContainText('Data type:');
 await expect(page.locator('.structure-card[data-kind="check"] text').filter({hasText:/Check \d|Prüfung \d/})).toHaveCount(0);
 await expect(page.locator('.structure-tree-row').filter({hasText:'Define successors'}).first()).toBeVisible();
 await page.screenshot({path:'qa/rule-network-ticket-en.png'});
 expect((await page.locator('.structure-card title').allTextContents()).some(s=>s.replaceAll('\\','/').includes(fixturePath.replaceAll('\\','/')))).toBe(false);
 await page.evaluate(()=>{settings.language='de';structure.refreshSettings();});
 await expect(page.getByRole('button',{name:'Alles einpassen',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Alles einklappen',exact:true}).click();
 await page.getByRole('button',{name:'Alles aufklappen',exact:true}).click();
 expect(await page.locator('.structure-card').count()).toBeGreaterThan(before);
 await page.evaluate(()=>structure.dispose());expect(errors).toEqual([]);
});
