import test from 'node:test';import assert from 'node:assert/strict';import {layoutNetwork,describeEdge,valueColor,routeOrthogonal,actionFor} from '../frontend/structure-network.js';
const n=(id,role,order,parent='action',extra={})=>({id,name:id,role,order,parent,kind:role==='scope'?'entry':'statement',...extra});
const edge=(from,to,kind='value',name='v')=>({from,to,kind,valueName:name,valueType:'int',label:'verwendet',labelEn:'uses'});
const nodes=[n('action','scope',0,''),n('input','input',1),n('other','input',2),n('first','rule',10),n('group','rule',20),n('child1','rule',21,'group'),n('child2','rule',22,'group'),n('after','rule',30),n('out','output',40)];
const edges=[edge('input','first'),edge('first','group','control'),edge('other','child2'),edge('child1','child2','control'),edge('child2','group'),edge('group','after','control'),edge('after','out')];
test('action focus, expanded descendants precede join and downstream rules',()=>{const l=layoutNetwork(nodes,edges,{focusId:'child1'});assert.equal(l.focusId,'action');assert.equal(actionFor(nodes,'child1'),'action');assert(l.cards.get('child2').x>l.cards.get('child1').x);assert(l.cards.get('group').x>l.cards.get('child2').x);assert(l.cards.get('after').x>l.cards.get('group').x);assert(l.cards.get('out').x>l.cards.get('after').x);assert.equal(l.cards.get('input').x,l.cards.get('other').x);assert(!l.cards.has('action'));});
test('collapse projects underlying endpoints without losing original hint provenance',()=>{const l=layoutNetwork(nodes,edges,{focusId:'action',collapsed:new Set(['group'])});assert(!l.cards.has('child1'));const e=l.edges.find(e=>e.sourceId==='other');assert.equal(e.to,'group');assert.equal(e.targetId,'child2');assert.match(describeEdge(e,nodes,'en'),/To: child2/);assert.equal(e.color,layoutNetwork(nodes,edges,{focusId:'action'}).edges.find(x=>x.sourceId==='other').color);});
test('one source value retains color across destinations; new value changes',()=>{assert.equal(valueColor(edge('a','b')),valueColor(edge('a','c')));assert.notEqual(valueColor(edge('a','b')),valueColor(edge('b','c')));assert.equal(valueColor(edge('a','b','control')),valueColor(edge('z','x','control')));});
test('hints are bilingual and unknown types never guessed',()=>{const e=edge('input','first');assert.match(describeEdge(e,nodes,'de'),/Datentyp: int/);assert.match(describeEdge(e,nodes,'en'),/Data type: int/);assert.match(describeEdge({...e,valueType:''},nodes,'en'),/Not statically determined/);assert.match(describeEdge({...e,kind:'control'},nodes,'de'),/kein Datentyp/);assert.doesNotMatch(describeEdge({...e,kind:'control'},nodes,'en'),/Data type: int/);});
function crosses(a,b,r){return a.x===b.x?a.x>r.x&&a.x<r.x+r.w&&Math.max(a.y,b.y)>r.y&&Math.min(a.y,b.y)<r.y+r.h:a.y>r.y&&a.y<r.y+r.h&&Math.max(a.x,b.x)>r.x&&Math.min(a.x,b.x)<r.x+r.w;}
test('all routed segments are orthogonal and avoid every card interior',()=>{for(const collapsed of[new Set(),new Set(['group'])]){const l=layoutNetwork(nodes,edges,{focusId:'action',collapsed});for(const e of l.edges){assert(e.path.startsWith('M '));for(let i=1;i<e.route.length;i++){const a=e.route[i-1],b=e.route[i];assert(a.x===b.x||a.y===b.y);for(const r of l.cards.values())assert(!crosses(a,b,r),JSON.stringify({e:e.key,a,b,r}));}}}});
test('routing detours around intervening card',()=>{const cards=new Map([['block',{x:150,y:50,w:200,h:120}]]);const points=routeOrthogonal({x:50,y:100},{x:450,y:100},cards);assert(points.some(p=>p.y<50||p.y>170));});
test('different actions never mix in focused network',()=>{const second=[...nodes,n('second','scope',0,''),n('alien','input',1,'second')];assert(!layoutNetwork(second,edges,{focusId:'first'}).cards.has('alien'));});

test('all actions retain real scope headers and colors are unique per source value',()=>{const second=[...nodes,n('second','scope',100,''),n('alien','input',101,'second'),n('end','output',102,'second')],allEdges=[...edges,edge('alien','end')];const l=layoutNetwork(second,allEdges,{focusId:'*'});assert(l.groups.some(g=>g.id==='action'));assert(l.cards.has('second'));assert(l.cards.has('alien'));assert(l.cards.get('alien').y>l.groups.find(g=>g.id==='action').h);const origin=new Map(l.edges.filter(e=>e.kind==='value').map(e=>[e.sourceId+'|'+e.valueName,e.color]));assert.equal(new Set(origin.values()).size,origin.size);});
test('explicit branch joins stay after their child instead of redirecting backwards',()=>{const joined=[...edges,edge('child2','group','control')];const l=layoutNetwork(nodes,joined,{focusId:'action'});const join=l.edges.find(e=>e.sourceId==='child2'&&e.targetId==='group'&&e.kind==='control');assert.equal(join.to,'group');assert(l.cards.get(join.to).x>l.cards.get(join.from).x);});
test('aliases of one input share a stable color across their uses',()=>{const l=layoutNetwork(nodes,[...edges,edge('input','after','value','self.v')],{focusId:'action'});const uses=l.edges.filter(e=>e.sourceId==='input');assert.equal(new Set(uses.map(e=>e.color)).size,1);});
test('different conditional guards survive projected edge deduplication',()=>{const guard=[edge('first','after','control'),{...edge('first','after','control'),label:'sonst',labelEn:'otherwise'}];const l=layoutNetwork(nodes,guard,{focusId:'action'});assert.equal(l.edges.filter(e=>e.from==='first'&&e.to==='after').length,2);});
test('actual ticket analyzer expands in forward order with semantic vertical lanes',async()=>{const {createRequire}=await import('node:module'),{readFileSync}=await import('node:fs'),{fileURLToPath}=await import('node:url');const require=createRequire(import.meta.url);const {structure}=require('../resources/assets/language/structure-service.js');const path=fileURLToPath(new URL('../resources/examples/catalog/tickets/tickets.ag',import.meta.url));const flow=structure({path,text:readFileSync(path,'utf8')}).flow;assert(flow);for(const action of flow.nodes.filter(n=>n.kind==='entry')){const l=layoutNetwork(flow.nodes,flow.edges,{focusId:action.id});for(const e of l.edges.filter(e=>e.kind==='control'))assert(l.cards.get(e.to).x>l.cards.get(e.from).x,e.label);const nodeMap=new Map(flow.nodes.map(n=>[n.id,n]));const isBelow=(id,parent)=>{let n=nodeMap.get(id);const seen=new Set();while(n&&!seen.has(n.id)){if(n.parent===parent)return true;seen.add(n.id);n=nodeMap.get(n.parent);}return false;};for(const edge of flow.edges.filter(e=>e.kind==='control'&&l.cards.has(e.from)&&l.cards.has(e.to)&&!isBelow(e.from,e.to))){for(const child of flow.nodes.filter(n=>l.cards.has(n.id)&&isBelow(n.id,edge.to)))assert(l.cards.get(child.id).x>l.cards.get(edge.from).x,child.name+' stays after '+nodeMap.get(edge.from).name);}const ruleYs=new Set(flow.nodes.filter(n=>n.role==='rule'&&l.cards.has(n.id)).map(n=>l.cards.get(n.id).y));assert(ruleYs.size>=3,'rules follow several actual input lanes');for(const e of l.edges)for(let i=1;i<e.route.length;i++)for(const r of l.cards.values())assert(!crosses(e.route[i-1],e.route[i],r),'actual ticket route avoids cards');}});
test('expanded constant fields cannot precede external prior source statements',()=>{const l=layoutNetwork(nodes,edges,{focusId:'action'});assert(l.cards.get('child1').x>l.cards.get('first').x);assert(l.cards.get('child2').x>l.cards.get('first').x);});


const hierarchy=[n('app','scope',0,'',{kind:'app'}),n('actor','scope',1,'app',{kind:'actor'}),n('state','scope',2,'actor',{kind:'state'}),n('field','input',3,'state'),n('action','scope',4,'actor'),...nodes.filter(n=>n.id!=='action')];
const membership=[edge('app','actor','contains'),edge('actor','state','contains'),edge('state','field','contains'),edge('actor','action','contains')];
test('whole-app scope hierarchy respects app actor action and state folds',()=>{let l=layoutNetwork(hierarchy,[...edges,...membership],{focusId:'*',collapsed:new Set(['app'])});assert.deepEqual([...l.cards.keys()],['app']);l=layoutNetwork(hierarchy,[...edges,...membership],{focusId:'*',collapsed:new Set(['actor'])});assert(l.cards.has('app')&&l.cards.has('actor'));assert(!l.cards.has('action'));l=layoutNetwork(hierarchy,[...edges,...membership],{focusId:'*',collapsed:new Set(['state','action'])});assert(l.cards.has('state')&&l.cards.has('action'));assert(!l.cards.has('field')&&!l.cards.has('input'));l=layoutNetwork(hierarchy,[...edges,...membership],{focusId:'*'});assert(l.cards.has('field')&&l.cards.has('input'));assert(l.groups.find(g=>g.id==='app').expanded);for(const group of l.groups.filter(g=>g.expanded)){const header=l.cards.get(group.id);assert(header.x>=group.x&&header.x+header.w<=group.x+group.w);assert(header.y>=group.y&&header.y+header.h<=group.y+group.h);}});
test('actor focus and optional action header preserve actual identity',()=>{const l=layoutNetwork(hierarchy,[...edges,...membership],{focusId:'actor'});assert(l.cards.has('actor'));assert(!l.cards.has('app'));const action=layoutNetwork(hierarchy,edges,{focusId:'action',includeScope:true});assert(action.cards.has('action')&&action.cards.has('input'));const bare=layoutNetwork(hierarchy,edges,{focusId:'action'});assert(!bare.cards.has('action'));});
test('membership is structural and no actor runtime edges are fabricated',()=>{const l=layoutNetwork(hierarchy,[...edges,...membership],{focusId:'*',collapsed:new Set(['actor'])});assert(l.edges.every(e=>e.kind==='contains'));assert.match(describeEdge(l.edges[0],hierarchy,'en'),/not execution order/);assert.doesNotMatch(describeEdge(l.edges[0],hierarchy,'en'),/Data type/);});
test('real cross-scope edges project to collapsed headers and preserve provenance',()=>{const second=[...hierarchy,n('actor2','scope',100,'app',{kind:'actor'}),n('second','scope',101,'actor2'),n('alien','input',102,'second')];const real=edge('out','alien','value','ticket');const l=layoutNetwork(second,[...edges,...membership,real],{focusId:'*',collapsed:new Set(['actor','actor2'])});const connection=l.edges.find(e=>e.sourceId==='out'&&e.targetId==='alien');assert.equal(connection.from,'actor');assert.equal(connection.to,'actor2');assert.equal(connection.valueName,'ticket');assert.match(describeEdge(connection,second,'en'),/From: out/);});
test('fully expanded actual ticket hierarchy routes avoid cards and only scope containment is drawn',async()=>{const {createRequire}=await import('node:module'),{readFileSync}=await import('node:fs'),{fileURLToPath}=await import('node:url');const require=createRequire(import.meta.url),{structure}=require('../resources/assets/language/structure-service.js');const path=fileURLToPath(new URL('../resources/examples/catalog/tickets/tickets.ag',import.meta.url));const flow=structure({path,text:readFileSync(path,'utf8')}).flow,l=layoutNetwork(flow.nodes,flow.edges,{focusId:'*'});const map=new Map(flow.nodes.map(n=>[n.id,n]));for(const e of l.edges){if(e.kind==='contains')assert(['app','actor','state','file'].includes(map.get(e.sourceId).kind));for(let i=1;i<e.route.length;i++){const a=e.route[i-1],b=e.route[i];assert(a.x===b.x||a.y===b.y);for(const[id,r]of l.cards)assert(!crosses(a,b,r),`${e.kind}: ${e.from} → ${e.to} crosses ${id}`);}}const rectangles=[...l.cards];for(let i=0;i<rectangles.length;i++)for(let j=i+1;j<rectangles.length;j++){const a=rectangles[i][1],b=rectangles[j][1];assert(a.x+a.w<=b.x||b.x+b.w<=a.x||a.y+a.h<=b.y||b.y+b.h<=a.y,'hierarchy cards do not overlap');}});
