import test from 'node:test';
import assert from 'node:assert/strict';
import {ScenarioSchema,parseValue,diagnoseFailure,parseScenario,stringifyScenario} from '../frontend/transactions.js';
import {renameChanges,sourceOffset} from '../frontend/structure.js';
const fixture={argent:{actors:[{name:'Counter',state:'CounterState',entries:[{name:'step',abi:{contract:'Counter',entry:'step'},hidden_params:[{name:'hidden'}],route_plan:{outputs:[{actors:['Counter']}]}}]}],states:[{name:'CounterState',fields:[{name:'count',type:{kind:'int'}},{name:'owner',type:{kind:'fixed_bytes',len:32}}]}]},sil_abi:{contracts:{Counter:{entries:{step:{params:[{name:'amount',type:{kind:'int'}},{name:'hidden',type:{kind:'int'}}]}}}}}};
test('ABI scenario preserves runtime format and excludes hidden parameters',()=>{const schema=new ScenarioSchema(fixture);assert.deepEqual(schema.create('Counter','step'),{version:1,inputs:[{actor:'Counter',entry:'step',state:{count:0,owner:'@test-hash:1'},args:[0],value:100000,sequence:0}],outputs:[{actor:'Counter',state:{count:0,owner:'@test-hash:1'},value:100000,authorizing_input:0}],funding:0,lock_time:0,artifacts:[]});assert.equal(schema.create('Counter','step',3).inputs[0].state.count,3);});
test('typed values reject loss of integer precision and invalid bytes',()=>{assert.equal(parseValue('255',{kind:'byte'}),255);assert.throws(()=>parseValue('256',{kind:'byte'}));assert.equal(stringifyScenario(parseValue('9007199254740993',{kind:'int'})),'9007199254740993');assert.equal(parseValue('@test-key:2',{kind:'sig'}),'@test-key:2');});
test('cross-file field rename changes indexed references and retains comments',()=>{const a={path:'a.ag',text:'int count; // count'},b={path:'b.ag',text:'require(count > 0);'};const node={id:'field',parent:'state',kind:'field',name:'count',renameSafe:true,references:[{path:'a.ag',start:4,end:9},{path:'b.ag',start:8,end:13}]};const model={nodes:[node],sources:[a,b]};const result=renameChanges(model,node,'value',[a,b]);assert.equal(result[0].text,'int value; // count');assert.equal(result[1].text,'require(value > 0);');assert.equal(a.text,'int count; // count');assert.throws(()=>renameChanges(model,node,'value',[{...a,text:'int other; // count'},b]),/geändert/);assert.throws(()=>renameChanges({...model,nodes:[node,{id:'another',parent:'state',kind:'field',name:'value'}]},node,'value',[a,b]),/vergeben/);assert.throws(()=>renameChanges(model,{...node,renameSafe:false},'value',[a,b]),/sicher/);});

test('bounded diagnosis retains failed verdict and never mutates scenario',async()=>{const scenario=new ScenarioSchema(fixture).create('Counter','step');const result=await diagnoseFailure(async copy=>({status:copy.outputs[0].state.count===1?'passed':'failed'}),scenario,{status:'failed',input:0});assert.equal(result.status,'failed');assert.equal(result.actor,'Counter');assert.equal(result.verified_alternative.to,1);assert.equal(scenario.outputs[0].state.count,0);});
test('bounded diagnosis limits expensive VM probes',async()=>{const scenario={inputs:[{actor:'A',entry:'go'}],outputs:[{actor:'A',state:Object.fromEntries(Array.from({length:20},(_,i)=>['f'+i,5]))}]};let probes=0;const result=await diagnoseFailure(async()=>{probes++;return{status:'failed'};},scenario,{status:'failed',input:0});assert.equal(probes,24);assert.equal(result.diagnosis_limited,true);});

test('full Int64 values survive form, JSON save/load and IPC string roundtrips',()=>{for(const literal of ['9223372036854775807','-9223372036854775808','9007199254740993']){const value=parseValue(literal,{kind:'int'}),encoded=stringifyScenario({inputs:[{state:{value}}]});assert.equal(encoded,'{"inputs":[{"state":{"value":'+literal+'}}]}');assert.equal(stringifyScenario(parseScenario(encoded)),encoded);}assert.throws(()=>parseValue('9223372036854775808',{kind:'int'}));assert.throws(()=>parseValue('-9223372036854775809',{kind:'int'}));assert.equal(typeof parseValue('42',{kind:'int'}),'number');});
test('diagnostic alternatives handle maximum Int64 without rounding or overflow',async()=>{const value=parseValue('9223372036854775807',{kind:'int'}),scenario={inputs:[{actor:'A',entry:'e'}],outputs:[{actor:'A',state:{value}}]},seen=[];await diagnoseFailure(async s=>{seen.push(stringifyScenario(s.outputs[0].state.value));return {status:'failed'};},scenario,{status:'failed',input:0});assert.deepEqual(seen,['9223372036854775806','0','1']);});

test('compiler source positions count Unicode scalars like the original details view',()=>{assert.equal(sourceOffset('line\n🌍 require(false);',2,3),8);assert.equal(sourceOffset('short',99,1),5);});
