import {test,expect} from '@playwright/test';
import {createServer} from 'vite';
let server,url;
test.use(process.env.ARGENT_BROWSER==='webkit'?{browserName:'webkit'}:{browserName:'chromium',channel:'msedge'});
test.beforeAll(async()=>{server=await createServer({server:{host:'127.0.0.1',port:0,hmr:false,watch:null},logLevel:'error'});await server.listen();url=server.resolvedUrls.local[0];});
test.afterAll(async()=>server?.close());
async function transaction(page){await page.goto(url+'locale-fixture');await page.setContent('<div id="host" style="height:700px"></div>');await page.evaluate(async()=>{const {openTestTransaction}=await import('/frontend/transactions.js');window.settings={language:'en'};const artifact={argent:{actors:[{name:'Transaktion',state:'S',entries:[{name:'Nachher',abi:{contract:'C',entry:'step'},route_plan:{outputs:[{actors:['Transaktion']}]}}]}],states:[{name:'S',fields:[{name:'Testfinanzierung',type:{kind:'string'}},{name:'Aufrufwerte',type:{kind:'int'}}]}]},sil_abi:{contracts:{C:{entries:{step:{params:[]}}}}}};window.build={success:true,artifact,artifactPath:'fixture/artifact.json'};window.docs=[{path:'fixture/main.ag',text:'actor Transaktion {}'}];window.failure=false;await openTestTransaction({getSettings:()=>settings,getBuild:()=>build,getDocuments:()=>docs,build:async()=>{},invoke:async()=>window.failure?{status:'error',message:'Transaktion Nachher Testfinanzierung raw diagnostic'}:{status:'passed',message:'All input scripts passed the local VM; runtime mass checks passed.'}},'Transaktion','Nachher');});await expect(page.getByRole('button',{name:'Check transaction',exact:true})).toBeVisible();}
test('transaction UI translates while identifiers and string source values remain exact',async({page})=>{await transaction(page);await expect(page.locator('.transaction-toolbar select')).toHaveText('Transaktion · Nachher');await expect(page.locator('.transaction-action-card strong')).toHaveText('Transaktion · Nachher');await expect(page.locator('.transaction-card h4').first()).toHaveText('Transaktion · Input 0 · Nachher');await expect(page.locator('.transaction-field span').filter({hasText:'Testfinanzierung · string'}).first()).toHaveText('Testfinanzierung · string');await page.locator('.transaction-column input:not([type])').first().fill('Transaktion Nachher');await page.getByRole('button',{name:'Check transaction',exact:true}).click();await expect(page.locator('.transaction-result')).toHaveValue(/PASSED/);await page.evaluate(()=>settings.language='de');await expect(page.getByRole('button',{name:'Transaktion prüfen',exact:true})).toBeVisible();await expect(page.locator('.transaction-result')).toHaveValue(/BESTANDEN/);await expect(page.locator('.transaction-card h4').first()).toHaveText('Transaktion · Eingang 0 · Nachher');await page.evaluate(()=>settings.language='en');await expect(page.locator('.transaction-result')).toHaveValue(/PASSED/);await expect(page.locator('.transaction-toolbar select')).toHaveText('Transaktion · Nachher');await expect(page.locator('.transaction-column input:not([type])').first()).toHaveValue('Transaktion Nachher');});
test('raw VM diagnostics and JSON survive both language directions',async({page})=>{await transaction(page);await page.evaluate(()=>failure=true);const json=await page.locator('.transaction-json').inputValue();await page.getByRole('button',{name:'Check transaction',exact:true}).click();await expect(page.locator('.transaction-result')).toHaveValue(/SCENARIO OR RUNTIME ERROR\nTransaktion Nachher Testfinanzierung raw diagnostic/);await page.evaluate(()=>settings.language='de');await expect(page.locator('.transaction-result')).toHaveValue(/SZENARIO- ODER RUNTIMEFEHLER\nTransaktion Nachher Testfinanzierung raw diagnostic/);await page.evaluate(()=>settings.language='en');await expect(page.locator('.transaction-result')).toHaveValue(/SCENARIO OR RUNTIME ERROR\nTransaktion Nachher Testfinanzierung raw diagnostic/);await expect(page.locator('.transaction-json')).toHaveValue(json);});
test('structure hint errors translate their prefix and preserve diagnostics on language changes',async({page})=>{await page.goto(url+'locale-fixture');await page.setContent('<div id="host" style="height:700px"></div>');await page.evaluate(async()=>{const {mountStructure}=await import('/frontend/structure.js');window.settings={language:'en'};window.doc={path:'fixture/readme.txt',text:'Transaktion source'};window.view=mountStructure(document.querySelector('#host'),{getSettings:()=>settings,getDocument:()=>doc,getDocuments:()=>[doc],invoke:async()=>{throw Error('Transaktion raw source');},getBuild:()=>null});});await expect(page.locator('.structure-hint')).toHaveText('Structure view is available for Argent files (.ag).');await page.evaluate(async()=>{doc.path='fixture/main.ag';await view.refresh();});await expect(page.locator('.structure-hint')).toHaveText('Unable to read structure: Error: Transaktion raw source');await page.evaluate(()=>settings.language='de');await expect(page.locator('.structure-hint')).toHaveText('Struktur konnte nicht gelesen werden: Error: Transaktion raw source');await page.evaluate(()=>settings.language='en');await expect(page.locator('.structure-hint')).toHaveText('Unable to read structure: Error: Transaktion raw source');});
