import {test,expect} from '@playwright/test';
import {createServer} from 'vite';
let vite,baseUrl;
test.beforeAll(async()=>{vite=await createServer({server:{host:'127.0.0.1',port:1455,strictPort:false,hmr:false,watch:null},logLevel:'error'});await vite.listen();baseUrl=vite.resolvedUrls.local[0];});
test.afterAll(async()=>{await vite?.close();});
test.use({channel:'msedge',viewport:{width:900,height:600}});
async function mount(page,{language='en',mode='available',dark=false}={}){
 await page.route('**/updater-fixture.html',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><link rel="stylesheet" href="/frontend/style.css"><link rel="stylesheet" href="/frontend/updater.css"></head><body></body></html>'}));
 await page.goto(baseUrl+'updater-fixture.html');
 await page.evaluate(async({language,mode,dark})=>{document.body.classList.toggle('dark',dark);const {createUpdater}=await import('/frontend/updater.js');window.calls=[];window.prepared=true;window.failInstall=false;window.update={version:'0.46.0',body:'Fixes\n<img src=x onerror=alert(1)>',close:async()=>calls.push('close'),downloadAndInstall:async callback=>{calls.push('install');callback({event:'Started',data:{contentLength:100}});callback({event:'Progress',data:{chunkLength:50}});await new Promise(resolve=>window.finishDownload=resolve);if(window.failInstall)throw Error('network');callback({event:'Finished'});}};window.updater=createUpdater({getSettings:()=>({language}),isSupported:()=>mode!=='unsupported',prepareUpdate:async()=>{calls.push('save');return prepared?()=>calls.push('unlock'):false;},check:async()=>{calls.push('check');if(mode==='error')throw Error('network');return mode==='none'?null:update;}});},{language,mode,dark});
}
test('startup offers a dismissible update with release text rendered safely',async({page})=>{await mount(page);await page.evaluate(()=>updater.checkForUpdates());await expect(page.getByRole('dialog')).toContainText('0.46.0');await expect(page.locator('.update-notes')).toContainText('<img');await expect(page.locator('dialog img')).toHaveCount(0);await page.screenshot({path:test.info().outputPath('update-light.png')});await page.getByRole('button',{name:'Later',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>calls)).toEqual(['check','close']);});
test('saving precedes installation; progress and closing are locked until completion',async({page})=>{await mount(page);await page.evaluate(()=>updater.checkForUpdates());await page.getByRole('button',{name:'Update now'}).click();await expect(page.getByRole('status')).toHaveText('Downloading: 50 %');expect(await page.evaluate(()=>calls)).toEqual(['check','save','install']);await expect(page.getByRole('button',{name:'Close',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await page.evaluate(()=>finishDownload());await expect(page.getByRole('status')).toContainText('Update installed');expect(await page.evaluate(()=>calls)).toContain('unlock');});
test('an incomplete save prevents installation',async({page})=>{await mount(page);await page.evaluate(()=>{prepared=false;return updater.checkForUpdates();});await page.getByRole('button',{name:'Update now'}).click();await expect(page.getByRole('status')).toContainText('not started');expect(await page.evaluate(()=>calls)).toEqual(['check','save']);});
test('failed downloads unlock editing and allow retry',async({page})=>{await mount(page);await page.evaluate(()=>{failInstall=true;return updater.checkForUpdates();});await page.getByRole('button',{name:'Update now'}).click();await page.evaluate(()=>finishDownload());await expect(page.getByRole('status')).toContainText('could not be completed');await expect(page.getByRole('button',{name:'Update now'})).toBeEnabled();expect(await page.evaluate(()=>calls)).toContain('unlock');});
test('offline startup is quiet while manual checks report failures',async({page})=>{await mount(page,{mode:'error'});await page.evaluate(()=>updater.checkForUpdates());await expect(page.getByRole('dialog')).toHaveCount(0);await page.evaluate(()=>updater.checkForUpdates({manual:true}));await expect(page.getByRole('dialog')).toContainText('Could not check for updates');});
test('German dark dialog fits a small window and Escape postpones',async({page})=>{await mount(page,{language:'de',dark:true});await page.evaluate(()=>updater.checkForUpdates());await expect(page.getByRole('button',{name:'Jetzt aktualisieren'})).toBeVisible();const box=await page.getByRole('dialog').boundingBox();expect(box.y).toBeGreaterThanOrEqual(0);expect(box.y+box.height).toBeLessThanOrEqual(600);await page.screenshot({path:test.info().outputPath('update-dark.png')});await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);});
test('manual check reports the current version without an install action',async({page})=>{await mount(page,{mode:'none'});await page.evaluate(()=>updater.checkForUpdates({manual:true}));await expect(page.getByRole('dialog')).toContainText('latest version');await expect(page.getByRole('button',{name:'Update now'})).toHaveCount(0);});
