// Generate machine-local Cargo settings without publishing personal build paths.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const mappings=new Map([[os.homedir(),'/build/user'],[root,'/build/argent-studio']]);
const flags=['-C','debuginfo=0'];
for(const [from,to] of mappings)flags.push('--remap-path-prefix='+from+'='+to);
if(process.platform==='win32')flags.push('-C','link-arg=/PDBALTPATH:%_PDB%');
fs.mkdirSync(path.join(root,'.cargo'),{recursive:true});
fs.writeFileSync(path.join(root,'.cargo/config.toml'),'# Generated by scripts/configure-build.mjs; do not commit.\n[build]\nrustflags = '+JSON.stringify(flags)+'\n');
console.log('Configured neutral compiler source paths.');
